### ISSUE TITLE
Removing an entry

### ISSUE THREAD

**Issue by pdm45** [Kungsgeten/org-brain#100]
Hi, I've been using org-brain to keep track of my projects, with 'friends' links to stakeholder names, parent links to geographical regions, and other very useful things. I also keep my project notes in the org-brain file.

Once a project is complete however I'd like to archive it rather than deleting so I have a reference back to my old notes without keeping it in my brain... I've found that to be very complicated, is there an easy way? Ideally I'd like a 'remove' option which tidied up all the hanging links without deleting the entry entirely so I could go and archive using the standard org command.

**Comment by pdm45** [comment]
org-brain-archive would be ideal - maybe it can use the value of org-archive-default-command to make it really slick.

**Comment by Kungsgeten** [comment]
I wasn't quite sure if I should use `org-archive-default` or `org-archive-subtree-default`. The subtree variant sounded more correct to me (and also seems to use `org-archive-default-command`). Anyhow the command `org-brain-archive` is now available :) Please try it out and let me know if there are problems.
