### ISSUE TITLE
Relationships between concepts spread across files no longer registering

### ISSUE THREAD

**Issue by circius** [Kungsgeten/org-brain#102]
Hello,

org-brain-visualize no longer shows relationships between concepts which are instantiated as files. Concepts instantiated as subheadings of a given file show relationships /within that file/, but lack references to concepts in other files. (those relationships are still expressed in the org-brain headers of the files in question.)

I don't think I made any significant changes to org-brain itself or to any relevant underlying systems before this bug expressed itself, although I have now updated to the latest release of org-brain.

Any help welcome! Although the brain isn't /that/ big, the files are intact, and I could probably recreate it by hand - if the thing's too obscure

It's great software, anyway. thanks a lot.

**Comment by circius** [comment]
Just a note to say that I've been able to reproduce this with a minimal example:

i) new brain-dir
ii) create concept index.org
iii) create child-concept "test.org" as file
iv) create "test2" concept as child-headline of test.org.

index.org shows no relationships in visualize; test2 and test show the correct relationships in visualize.

**Comment by Kungsgeten** [comment]
Hi! This sounds strange. The example you describe works for me. Do you get some kind of error message?

**Comment by circius** [comment]
No, *Messages* is quiet.

**Comment by Kungsgeten** [comment]
If you haven't updated in a while, it could be because of a bug I introduced a while back. This was fixed April 11th though.

**Comment by circius** [comment]
Whoops, that was it. Forgot to restart the emacs daemon after upgrading the package. Long day - sorry for the bother, and thanks.
