### ISSUE TITLE
Sorting titles in normal view mode...

### ISSUE THREAD

**Issue by usharf** [Kungsgeten/org-brain#103]
Use case: I'd like to be able to have titles of nodes sorted when buffer is visualized in normal "outline" mode.

Is there an option to keep title sorted in normal visualization (ie. not mindmap visualization). In org I can select heading and sort in many ways, including on a particular property.  For example, I might set a "timeline" property, and would like it to be used when headings are sorted.

**Comment by Kungsgeten** [comment]
Hi!

Good suggestion! I've added a commit which adds the possibility of sorting relationships, when visualizing. It doesn't matter if its the standard view or mindmap view. By default it will order by the title of the entries.

If you'd like to sort according to a property (like your example) you can write a function which takes two entries as arguments. The function should return if the first entry is smaller than the second (if it should come before the second when sorting). You can then set the variable `org-brain-visualize-sort-function` to that function.

I understand that this is a bit complex, it would be nice to have several functions to choose from (like `org-mode` have). If you have ideas on useful functions for sorting, or if you write any yourself, I'm interested!

**Comment by usharf** [comment]
Great, thanks! I'll have a look.
