### ISSUE TITLE
Pinned items/topic seem to be global

### ISSUE THREAD

**Issue by usharf** [Kungsgeten/org-brain#104]
It seems that items I've pinned in one "brain" (folder), show up in visualization of other "brains", ie. after using `org-brain-switch-brain`... is this by design?

**Comment by Kungsgeten** [comment]
Hmm, no that shouldn't be the case. From examining the code I *think* this could happen if you switch from a brain with pins, to one that doesn't have any pins. I'll add a commit which hopefully fixes this (I haven't used `org-brain-switch-brain` much myself).

**Comment by Kungsgeten** [comment]
The commit has been added. Please try it out and see if it works :)

**Comment by usharf** [comment]
OK, works for me.
Only issue was old pinns were removed.
After pinning new topics, switching and re-opening it seem to behave as expected!

Thanks
