### ISSUE TITLE
Mapping the org-brain files using dot.

### ISSUE THREAD

**Issue by cnngimenez** [Kungsgeten/org-brain#105]
I created a [fish](https://fishshell.com/)+ GAWK script for mapping the org-brain files structure into a dot file and creates the PNG image. 

It support drawing parent-childrens and friends relationships. It does not draw parent-children created with `org-brain-new-child` (represented by internal Org headers instead files).

Here's is the snippet: https://bitbucket.org/snippets/cnngimenez/nezarx#orgbrain2dot.fish

Maybe you can use the GAWK or the whole script for creating the map image. 

Cheers!

**Comment by Kungsgeten** [comment]
Sounds like a nice tool :) I haven't used Fish nor GAWK (and not many other bash scripts either), so I don't know if I'll be able to adapt the code. I have however tried to generate dot-files from emacs lisp, which worked okay. The problem was that I couldn't get it to look the way I wanted. Would you mind posting a picture of the resulting image?

**Comment by cnngimenez** [comment]
Maybe I can help in making an Elisp script in my free time. It needs to:

1. Create a temporal file and add a header string.
2. Apply the GNU AWK script into each Org file for creating the dot nodes and edges.
3. Add a footer.
4. Call dot to the temporal file.

I believe that is easier to call `gawk` to each file instead of using Elisp processing. Despite all, `gawk` (or `awk`) is common to al GNU/Linux systems.

<br/>
The fish script can be executed like this: (First, edit paths inside the file)

```fish
source orgbrain2dot.fish
brain-create-map
```

Here's an extract: 
![org-map-small](https://user-images.githubusercontent.com/1332276/40210677-aba35122-5a1c-11e8-9d76-f054ce28cb6c.png)

Where:
* Green nodes are files, non-green are mentioned in BRAIN_CHILDREN.
* Black edges are children defined  by BRAIN_CHILDREN
* Blue edges are parents defined by BRAIN_PARENTS
* Green edges are friends defined by BRAIN_FRIENDS

**Comment by cnngimenez** [comment]
Hi, I have just created an elisp code for making the dot files (instead of using fish and GNU AWK). I uploaded the file as a gist [here](https://gist.github.com/cnngimenez/16f0a592fb93b50eb03ded9a4a02d4be).

Maybe you can add it to org-brain as separates commands or use some of the functions to create the diagrams for better visualization. 

# Usage
It provides two interactive commands:

* `M-x obdot-relative-diagram` which asks for an entry name and make a diagram with the parents and children of it.
* `M-x obdot-subtree-diagram` which asks for an entry name and make all the subtree starting from it.

# Requirements
You need `dot` program (Graphviz package) and a temporal directory (it is setted as `~/tmp/` by default, see the constant `obdot-temp-dir` in the file).

**Comment by benjaminwd** [comment]
Do you have thoughts on updating this for the new edge labeling feature?

**Comment by theottm** [comment]
@cnngimenez I would like to try to use it in the coming days. Is it still up to date ? Is it planned to get added to the main branch of org-brain @Kungsgeten ?

**Comment by Kungsgeten** [comment]
I haven't tried the code in the linked gist. At the moment I'm not working on any exporting functionality, but others seems to be doing so (see #226). There's many external tools for graphs, mind-maps, etc, so I don't really know what an "official" export feature should look like.

**Comment by theottm** [comment]
I see. Thanks for the quick answer. I will also try out the solutions being mentioned in the issue. It's getting interesting :)

**Comment by michaelsjackson** [comment]
> # Usage
> 
> It provides two interactive commands:
> 
>     * `M-x obdot-relative-diagram` which asks for an entry name and make a diagram with the parents and children of it.
> 
>     * `M-x obdot-subtree-diagram` which asks for an entry name and make all the subtree starting from it.
> 
> 
> # Requirements
> 
> You need `dot` program (Graphviz package) and a temporal directory (it is setted as `~/tmp/` by default, see the constant `obdot-temp-dir` in the file).

Tried it quickly, after adding two closing paranthesis it seems to work, however friend-links are not appearing anywhere on the png image? I tried both variants, relative and subtree. If friend links would appear, that would be a great start. Thanks for sharing your code!

**Comment by Kungsgeten** [comment]
@cnngimenez @benjaminwd I've started a new repository named [org-brain-export](https://github.com/Kungsgeten/org-brain-export). I think discussions focused on exporting could be moved there. A starting point could be: https://github.com/Kungsgeten/org-brain-export/issues/2

I'm closing this since I think export discussions could take place there.
