### ISSUE TITLE
Support window switch

### ISSUE THREAD

**Issue by cnshsliu** [Kungsgeten/org-brain#109]
With Spacemacs, when I am in Org-brain visualize window, would like to use <Leader>0..9 to switch window

**Comment by usharf** [comment]
`org-brain` is supported as part of the `org` layer but it's true that the key mappings are not ideal/compatible. Essentially when in `org-brain` mode, I need to remeber to prefix everything global to `spacemacs` with `Alt+m`, to escape `evil-mode`, or I take a chance of messing things up in `org-brain` inadvertently.

**Comment by cnshsliu** [comment]
Thanks a lot, I will try to add keys to org-brain-visualize-mode-map.
