### ISSUE TITLE
[Feature] Jump/related links

### ISSUE THREAD

**Issue by rsuhada** [Kungsgeten/org-brain#11]
The Brain has one more type of links beyond child, parent - jump links. These link nodes that are related but not in a child/parent relation. E.g.: "hot" and "cold" are related in this way, or "Barack Obama" and "Michelle Obama".

It would be great to have this type too. (I think it could be done simly copying the "child" infrastructure and renaming it to e.g. "related", having :brainrelade: tags and headers. Nicer way would be to generalized the child functions to have a child/related switch)

Thanks!

**Comment by Kungsgeten** [comment]
I want to include these, but it is a bit problematic since they're two way. Which file should hold the relations? If adding some kind of database, this is a feature that I'd definitely add.

**Comment by rsuhada** [comment]
With flat files - both files would hold the link. If a.org is related to b.org then a.org will have in its brainrelated heading a link to b.org and, b.org in its heading a link to a.org.

By the way - this could be useful for child-parent relationships. Currently child is stored, but parents could be too. So if a.org is parent of b.org:

a.org has in brainchildrend b.org
b.org has in brainparents a.org

So links are always two-way. They are symmetric for related links (related-related) and antisymmetric for parent-child links.

This approach has 2 advantages:
1. since parent state is persisted, you don't need to search for it - just read it off the file (faster, scales better)
2. if you visit the given org file directly in org mode (not in brain-visualize) you still can see it's parents. Currently only children are visible.

These are just some thoughts... the implementation might be more complicated?

**Comment by Kungsgeten** [comment]
Yes, I've thought about storing parent links locally too, it would remedy the speed issues. The problematic thing is when adding/deleting a child link manually; the current file then needs to be added/deleted as a parent in the target as well. Its probably possible to do this in the save hooks, but I haven't tried it yet.

**Comment by Kungsgeten** [comment]
I have rewritten `org-brain` from scratch, please see: https://github.com/Kungsgeten/org-brain/tree/org-brain-id

This new version includes the "jump link" feature (but I call them friends). This will be merged into main in a couple of days, I'm just going to test it a bit more first.

**Comment by Kungsgeten** [comment]
The 0.4 branch is merged into master, and adds "jump links" as friendships.
