### ISSUE TITLE
Alignment issue in entry content visualization

### ISSUE THREAD

**Issue by usharf** [Kungsgeten/org-brain#111]
It's not a huge problem (visual distraction), but might be an easy fix? The visualization of an "Entry" is skewed a little bit, like can be seen in the example screenshots (the lines should be aligned.)

I thought it might have to do with the content being bidi (right-to-left), but like you can see in the last screenshot, that's not the case...

![gnome-shell-screenshot-ez2xiz](https://user-images.githubusercontent.com/1701421/40242126-0b080fc2-5abd-11e8-8355-e697e7c8db71.png)

![gnome-shell-screenshot-4uztiz](https://user-images.githubusercontent.com/1701421/40242330-b1c53bf0-5abd-11e8-9939-4bd262cfe2eb.png)

This is the org file behind:

![gnome-shell-screenshot-eq0uiz](https://user-images.githubusercontent.com/1701421/40242149-19fcf448-5abd-11e8-9a7a-b962443c8f5b.png)

**Comment by Kungsgeten** [comment]
Hmm, it might have something to do with the text being indented in the `org` file? I'm not indenting text myself in `org-mode`, so I haven't tested that very much. When looking at the code, I see there might be a bug. I'll commit a quick fix and we'll see if that helps.

**Comment by Kungsgeten** [comment]
The commit has been done. Please try it out and see if it solves the problem :)

**Comment by usharf** [comment]
Perfect :+1: 

![gnome-shell-screenshot-ecghjz](https://user-images.githubusercontent.com/1701421/40467217-42b7b8da-5f29-11e8-831b-b98e1339968f.png)
