### ISSUE TITLE
Option to show/hide tags

### ISSUE THREAD

**Issue by ghost** [Kungsgeten/org-brain#112]
The visualization buffer displays the tags of a headline, if they exist. I think it's useful, but probably would be able helpful if there's also an option to hide them, if they clutter the display of content.

**Comment by Kungsgeten** [comment]
This could be done. Do you have an idea where to show them? I'm thinking perhaps between the Friends and the Children of the entry? Or maybe to the right of the arrow pointing down at the entry. Not sure how to show it if in "mind map mode".

**Comment by usharf** [comment]
Did something change? I no longer see the tags in the org-brain buffer...
![gnome-shell-screenshot-a4vtjz](https://user-images.githubusercontent.com/1701421/40468460-cb247e70-5f2d-11e8-98dd-5392079b1d64.png)

**Comment by usharf** [comment]
I think in either visualizations it might be helpful to keep the tags near the topic itself at least? Or hide them, if needed.

When zoomed into a topic (sorry, not sure what's the right term), I guess having a "TAGS:" line might be also useful.

![gnome-shell-screenshot-vx9pjz](https://user-images.githubusercontent.com/1701421/40487623-0c7b8332-5f65-11e8-80b4-a59141105948.png)

![gnome-shell-screenshot-c1udjz](https://user-images.githubusercontent.com/1701421/40487740-5dd2ea86-5f65-11e8-82cc-455bb7b18067.png)

**Comment by Kungsgeten** [comment]
It is now possible to visualize the tags of entries. See "Customizing the look of entry titles" in the README.
