### ISSUE TITLE
New headlines always last

### ISSUE THREAD

**Issue by osktyn** [Kungsgeten/org-brain#113]
Whenever I add a new headline it always ends up as last entry instead of where it should be. It hasn't always been like this, but I don't know why the issue started. I've tried to remove all generated files but that doesn't seem to make a difference.

I am not sure if this is a bug or something I did, but suggestions to test which one it is would be welcome.

**Comment by Kungsgeten** [comment]
Does the new headline end up at the bottom of the file, instead of where it belongs? I don't know why this would happen, sorry. It might have something to do with how you have configured `org-mode`, `org-brain`, or some other part of Emacs.

**Comment by osktyn** [comment]
Always at the bottom of file.

I have copy-pasted everything except the id's to a duplicate folder and that did the trick. 

Closing, but if anyone gets a similar issue it is probably related to having duplicate IDs in your brain and regular org-files. However that happens.
