### ISSUE TITLE
Graphviz for visualizing mind map

### ISSUE THREAD

**Issue by falematte** [Kungsgeten/org-brain#115]
I believe that this would be a huge improvement to the visualization feature of  org-brain. Several emacs utilities could be used to achieve this result.

**Comment by Kungsgeten** [comment]
I've done some experimenting with this, but I found it hard to place the nodes in the map the way I wanted them to (so it is easy to see which nodes are parents, children, siblings, and friends to the visualized entry). If you (or anyone else) can make a mock-up in Graphviz of how it all could look, then it would probably be possible to include it in `org-brain`.

What are the emacs utilities that you're talking about?

**Comment by Kungsgeten** [comment]
Also see #105

**Comment by falematte** [comment]
Here are some tools: https://www.reddit.com/r/emacs/comments/8m1y2d/org_mode_exporter_to_graphviz/

I think any of the diagrams used as example would be a nice mock up. Anyway I do not really know how much work this will cost... Anyway thank you for the answer!

**Comment by falematte** [comment]
Update! Probably this is useful: https://github.com/theodorewiles/org-mind-map

**Comment by Kungsgeten** [comment]
I'm not really sure what's being requested. Is it to export all entries in `org-brain` to a single GraphViz diagram, or is it to show part of the diagram inside of Emacs (kind of a replacement for the current `org-brain-visualize`)? I think `org-mind-map` and similar solutions are more similar to the first use case.

**Comment by falematte** [comment]
I am talking about the second option. After you generate a pdf or a jpg with the diagram you can open it inside a buffer without leaving emacs.

**Comment by cnngimenez** [comment]
@falematte, I created an elisp code for something like you requested. See the issue #105 where I have written [a comment](https://github.com/Kungsgeten/org-brain/issues/105#issuecomment-405690839) with the gist link and some usage info.

Cheers!

**Comment by Kungsgeten** [comment]
I've started a new repository named [org-brain-export](https://github.com/Kungsgeten/org-brain-export). I think discussions focused on exporting could be moved there. A starting point could be: https://github.com/Kungsgeten/org-brain-export/issues/2

I'm closing this since I think export discussions could take place there.
