### ISSUE TITLE
Inconsistency with org comments

### ISSUE THREAD

**Issue by EFLS** [Kungsgeten/org-brain#116]
First of all, I'm sure you've heard this already but many thanks Kungsgeten for this awesome package.
I've been using it for a month now, and am migrating more and more of my notes into the brain. Awesome.

I ran into the following inconsistency when `org-brain-visualize` displays contents of an entry.

When the entry is a heading, any commented text (lines with `#`)  is still shown in the visualize buffer - which comes in handy, as these lines often contain important notes.

When the entry is a file, however, these comments are not shown in `org-brain-visualize` (while normal text is, of course, displayed).

This is not really much of an inconvenience, but I just wanted to let you know.

**Comment by Kungsgeten** [comment]
Hi! Sorry for the late response. The reason comments doesn't show is because of a regex I have (since lines starting with `#+` shouldn't show). I could probably modify the regex, but I'm a bit afraid that it would break something :) I'll see what I can do!

**Comment by EFLS** [comment]
Thanks for the reply.

Since my original comment, I've learnt to put limit the number of files, and put brain-notes mostly under different (sub)headings rather than in separate files. That is the way `org-brain` works best (as it allows for easier manipulation and movement of notes), so my earlier remark really isn't a priority bug.

**Comment by naclander** [comment]
@Kungsgeten , possibly related to #95 ? 

It seems maybe formatting what and what will not be displayed in `org-brain-visualize` can cause some issues ( or at minimum, different behaviors than users expect ).

**Comment by Kungsgeten** [comment]
This should be fixed now.
