### ISSUE TITLE
Can't figure out how to use attach

### ISSUE THREAD

**Issue by Trevoke** [Kungsgeten/org-brain#124]
I can only use it on headline entries, but I also can't figure out how to get those to show up?

**Comment by Kungsgeten** [comment]
The attach feature of `org-brain` is just using `org-attach`, which is a command provided by standard `org-mode`. Attachments only works on headlines, so that's why it only works on headline entries in `org-brain`. What do you mean by that you can't figure how to get them to show up?

**Comment by Trevoke** [comment]
So, if I have a regular org-mode file (the cursor is `|`) I can have:

`* Foo|` 

And then `M-x org-attach` and go through the process.

`org-brain-visualize-attach` only works in the org-brain buffer

My understanding is that org-brain's attach feature will only work from the org-brain buffer, like all the other org-brain -- but if I create a headline in the org mode buffer and then I refresh the org-brain visualize buffer, the headline doesn't show up:

![image](https://user-images.githubusercontent.com/67913/47922045-784e8680-de8c-11e8-803c-9c75e4efef78.png)

So I don't think I can use the feature?

**Comment by Trevoke** [comment]
Okay, I figured it out. It's an org-brain-headline, not just a headline entry; it needs an org-id. I had to search for `headline` in the readme to figure out what was different. Gonna open a PR to suggest a change to the README.
