### ISSUE TITLE
Use different face for headlines, files, etc

### ISSUE THREAD

**Issue by montaropdf** [Kungsgeten/org-brain#125]
Using different faces following the type of entry displayed in the graph would allows for a better understanding of ones entries organisation.

**Comment by Kungsgeten** [comment]
Now there's different faces for many of the things in the graph. There's no separation regarding file and headline entries though.

**Comment by gmenzel** [comment]
I would love being able to set different faces for file and headline entries.

**Comment by drbronner** [comment]
I have implemented this functionality, and will merge it in over the next few days.
