### ISSUE TITLE
Code blocks don't show up?

### ISSUE THREAD

**Issue by Trevoke** [Kungsgeten/org-brain#127]
After visualizing an entry and hitting `o` I type a simple org code block and then I save the org file and refresh the org-brain buffer, but nothing shows up:

![image](https://user-images.githubusercontent.com/67913/47921575-51dc1b80-de8b-11e8-88b5-27506ae2aeea.png)

Am I ... Using it incorrectly?

**Comment by Trevoke** [comment]
Okay, so .. I can get the src block to show up if I put it beneath an org-brain headline entry, not just as part of the file entry.

**Comment by Kungsgeten** [comment]
Hmm, that's strange. I think that source blocks should be visualized even in file entries. Thanks for reporting this.

**Comment by Kungsgeten** [comment]
It isn't working in file entries due to how `org-brain-text` is implemented. I'll see if I can fix that.

**Comment by Fibrasek** [comment]
Not only code, but any chunk of:
```
#+BEGIN
Text
#+END
```

make the entry disappear. For example I write a lot of step-by-step documentation:

```
- Run this command =touch some_file.txt=

- Add this to the file:

#+BEGIN
Some text
#+END

- Save and open the file with this command =vim some_file.txt=
```
The first and last entry show up, but the middle one, don't. Sometime only the one after the last `begin/end` block show up.

**Comment by sheepduke** [comment]
I got the same problem here.

Also the following formats cannot be rendered:

- Headlines. Source: `* Headline`
- Bold text. Source: `*bold text*`
- Italic text. Source: `/text here/`

Surprisingly inline code works: `~code here~`

**Comment by delaanthonio** [comment]
Are there any updates for this issue?

**Comment by Kungsgeten** [comment]
@delaanthonio Sorry, but I haven't tried to solve it. I've been thinking about removing the support for file entries (which would solve the problem, since only file entries has this issue), but it seems like a lot of users use them so I probably won't do that.

**Comment by Trevoke** [comment]
I'm pretty sure @Kungsgeten knows this but just in case for others:

If you add the `:showchildren:` tag you can then see things like code blocks -- but then you can't have things like headline entries because everything will just be rendered as text. It's not quite a fix but it's at least a temporary workaround: it'll work for _some_ entries.

**Comment by Trevoke** [comment]
If there were tests I'd feel more comfortable jumping into this project to try and help but, as-is, I'm a little worried that I'd accidentally break something.

**Comment by sheepduke** [comment]
Since this problem really affects my experience, I decided to roll my own.

See here:
https://github.com/sheepduke/silver-brain

**Comment by Kungsgeten** [comment]
I think this should be fixed now.

**Comment by Trevoke** [comment]
Nice, thank you!
