### ISSUE TITLE
Can't deploy by Travis CI

### ISSUE THREAD

**Issue by emuio** [Kungsgeten/org-brain#13]
Hello.When I add the config which auto install 'org-brain' by the function 'package-install',my Emacs App can start up correct. But the Travis CI tell me 'The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).'
Can you help me, thanks.
The log page: https://travis-ci.org/emuio/emacs.d/jobs/222531880

**Comment by Kungsgeten** [comment]
It seems like you do not have Emacs 25, which org-brain requires.

**Comment by emuio** [comment]
Maybe it isn't this reason. The Travis config:

```
{
  "language": "ruby",
  "before_install": [
    "git clone https://github.com/rejeep/evm.git $HOME/.evm",
    "export PATH=$HOME/.evm/bin:$PATH",
    "evm config path /tmp",
    "evm install $EVM_EMACS --use --skip"
  ],
  "env": "EVM_EMACS=emacs-25.1-travis",
  "script": "lsb_release -a && ./test-startup.sh",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
```

**Comment by Kungsgeten** [comment]
I have never used Travis myself, so I'm afraid I can't help you :(

**Comment by Kungsgeten** [comment]
I'm marking this as closed for now, since I do not think this is an `org-brain` problem.
