### ISSUE TITLE
Gradually migrating a custom org wiki of ~2200 pages to org-brain, performance issues

### ISSUE THREAD

**Issue by fullofcaffeine** [Kungsgeten/org-brain#130]
Hi!

First of all, thanks for working on and releasing `org-brain`. It's a great piece of software, and something I've been wanting to see in Emacs for quite a while!

I have a homebrew wiki in Emacs and I'm trying to gradually convert it to `org-brain`. The wiki consists of around ~2200 org files in a directory. Each file is represents a wiki "page" and I have some glue code that allows me to link from other files in the same directory using the simple `[[]]` syntax  (i.e OrgMode.org can be linked from other wiki org files in the same dir by simple writing `[[OrgMode]]`).

I also have a projectile setup pointing to it and each wiki org page has a `* tags` heading with a list of tags + I have an `index.org` file that lists all of the wiki org files with the same tags. This allows me to find the wiki org files from the agenda (because `index.org` is included in it) or using `grep` because the tags are duplicated in each of the pages in the `* tags` header item).

Example of a wiki org page:

`File name: SciKit.org`
```
* tags :scikit:python:ml:machinelearning:datascience:
* [[Python]]
* [[DataScience]]
* Foo
* Bar
More content
```

Then there's a corresponding entry in the `Index.org`:

`File name: Index.org`
```
* Python  :scikit:python:ml:machinelearning:datascience:
<2017-10-10 10:00PM>
[[/path/to/Python.org]]
```

It's been working well over the years, but it lacks the visualization and relationship aspect. I do link to other related wiki pages, but there's no formal way to visualize the graph.

I'd like to slowly convert the wiki to be `org-brain`-compatible,  I started by pointing the `org-brain-path` var to the wiki folder. I didn't expect it to work, but it's usable to the point of `org-brain` recognizing each org file as a brain "node". Relationships, of course, aren't there yet and that's what I'd like to gradually add. 

However, I'm having serious performance problems at the moment. `org-brain-visuaze` takes around 6 minutes the first time I run it (and I'm on a rather powerful laptop, the XPS15 with 32GB of RAM, i7 6700HQ), after that it seems to run quicker at around 50 seconds for each run, but all other commands, like add child, also take ~20secs.

I'm not sure why this is happening though. I'd expect `org-brain` to mostly ignore these file contents as they don't have the format it expects (except for attachments). 

Is there anything I could do to improve the performance at this point? Am I missing something? Maybe I should try another approach instead of pointing `org-brain` to my existing wiki folder? Or is `org-brain` not prepared to deal with that many files at all, right now? I'd *love* to start using `org-brain`, so any insights would be greatly appreciated.

System and software info:

```
OS: Linux Mint 18.3 Cinnamon 64bit
Linux kernel: 4.15.0.32-generic
Processor: i7-6700HQ @ 2.60GHz x 4
Memory: 32GB
HD: 1TB, 550GB free
Emacs version: 26.1
Orgmode version: 9.1.14
```

Thanks in advance!

**Comment by fullofcaffeine** [comment]
UPDATE: Looks like the problem is indeed the number of files. I created a new empty brain directory, set the path var to it and created 2000 dummy empty org files, and `org-brain-visualize` also takes around 6min in the first run. So it wasn't because of the contents of the wiki pages necessarily, but the number of files, it seems.

**Comment by yuhan0** [comment]
I've been experiencing distinct increases in lag as well after adding more files, and dug a little into this - it turns out the `org-brain--headline-entries` function is making Emacs run expensive find-file hooks and mode initialization on every file in the list, just to grab their headline titles and IDs.  

Here's a refactoring of the two relevant functions which just uses overwrites on a temporary buffer, it reduced the wait time from ~10 seconds to nearly instantaneous on my side. Let me know if it works well for you :)  

```emacs-lisp
(defun org-brain--headline-entry-at-point ()
  "Get headline entry and ID at point."
  (unless (org-brain-entry-at-point-excludedp)
    (when-let ((id (org-entry-get (point) "ID")))
      (list (org-brain-headline-at (point)) id))))

(defun org-brain-headline-entries ()
  "Get all org-brain headline entries."
  (with-temp-buffer
    (org-mode)
    (let ((entries
           (mapcan
            (lambda (file)
              (insert-file-contents file nil nil nil 'replace)
              (mapcar (lambda (entry)
                        (and entry (cons (org-brain-path-entry-name file) entry)))
                      (org-map-entries #'org-brain--headline-entry-at-point)))
            (org-brain-files))))
      (remove nil entries))))
```

**Comment by Kungsgeten** [comment]
@yuhan0 I tried your code and it seems to be working pretty well! I don't have a huge amount of files/entries myself, but noticed an improvement (especially with the first call to `org-brain-visualize`). I'll try to commit the code (or some version of it) sometime today or during the weekend.

**Comment by yuhan0** [comment]
Glad to hear that :) 
I only have about twenty files in total, but I'm using Spacemacs which runs a hundred different hooks on each one (projectile, magit, window configuration hooks, modeline refreshes, etc etc.), so it made a big difference there. 
If you prefer I can send a quick PR as well with those 2 function changes

**Comment by Kungsgeten** [comment]
Its fine, I can change it myself (if that's fine with you). I'll probably
need to change the docstring and function name of the help function (since
it doesn't return the entry anymore).

**Comment by Kungsgeten** [comment]
The commit has been made! Thanks @yuhan0! I made some minor changes to your code, which you can see in the commit. What I noticed on my system is that the first run is much faster, but that the following runs are a bit slower than before. I think this is because `org-brain` opens all files in separate buffers, and the next time doing this they're already open. With the new implementation the time is always the same.

The next optimization step would probably involve some kind of caching of entries.

**Comment by fullofcaffeine** [comment]
Hey guys!

Thank you for the replies!

I actually made a quick and dirty hack to org-brain to temporarily solve the issue. I disabled the title by headline flag and for the `org-brain-add-[parent, child, friend]` functions, I removed the portion that would iterate over the files in the directory to provide suggestions. I then ended up with an instant prompt that will not suggest the filenames, but since I use projectile in the same dir, I can quickly list all the files. With the change, org-brain becomes very useable for me.

There is some very light rendering slowdown in nodes that have lots of parents, but it's not to point of making it unusable and that's another problem not really related to this one.

@yuhan0 @Kungsgeten 
I'll see if I have time to try the new change this weekend, if it can solve the issue and provide me with the completion suggestion in a reasonable amount of time, then it'd be much better than my hack.

**Comment by fullofcaffeine** [comment]
Update: I'm still using my hacked branch that doesn't provide the name suggestions (see description of how I've done it above). @Kungsgeten I didn't have time to try the newer versions, so you may close this issue for now if it has been fixed already, or leave it as a placeholder if it hasn't. Thanks!

**Comment by Kungsgeten** [comment]
I've made another optimization which reduces the time to get all the entries when visualizing etc. On my machine, benchmarking with 265 entries * 10 (so 2650 entries) takes about 2.7 seconds (2.4 seconds if setting `org-brain-file-entries-use-title` to nil). Its probably possible to optimize even more, but for the moment I'm closing this.

**Comment by fullofcaffeine** [comment]
HI @Kungsgeten, thanks for looking into it. I've tried the version @ HEAD and it's still too slow for me though, although I can see the performance has improved. I'll keep using my fork for now.
