### ISSUE TITLE
jump to org-brain from org-mode file

### ISSUE THREAD

**Issue by yuchen-lea** [Kungsgeten/org-brain#135]
Now, thanks for the `org-brain-goto-current`, we can easily go to related org entry from org-brain buffer. If we can also go to the org-brain page directly from org entry, that would be great! Since I have so many headlines, `M-x org-brain-visualize` -> search takes some time.
Thanks for your time!

**Comment by Kungsgeten** [comment]
I'm currently on the phone, so I haven't tested the code below. I think this command will do what you want. Try adding it to your init.el

(defun org-brain-visualize-current ()
  (interactive)
  (org-brain-visualize (org-brain-entry-at-pt)))

**Comment by yuchen-lea** [comment]
Thanks for your solution! but it raises `helm-M-x: Not in a brain file`

**Comment by yuchen-lea** [comment]
Aha, finally, I found that `org-brain-path` is `notes\` while `buffer-file-name` is `Notes\`， it's case sensitive. Working really well :D

**Comment by Kungsgeten** [comment]
I'm reopening since the could perhaps be added to the package, or at least in the README.
