### ISSUE TITLE
Remove child relation without remove entry

### ISSUE THREAD

**Issue by yuchen-lea** [Kungsgeten/org-brain#136]
`org-brain-remove-child` will remove both the child relations and the child entry. I want to keep the entry while remove the relation only. Since I want to keep org-brain like wiki, the wiki PAGE as brain node. BUT, I often refered to the sections in the page, then the link is generated and the SECTION shows up.

Now, I have to add `nobrain` tag manually.  Is there a more convenient way?

**Comment by Kungsgeten** [comment]
Closing this since I don't understand the issue, and I haven't received clarifications in 6 months.
