### ISSUE TITLE
what should i add to .emacs if Idon't use use-package?

### ISSUE THREAD

**Issue by longlu** [Kungsgeten/org-brain#139]
what should i add to .emacs if Idon't use use-package?

**Comment by longlu** [comment]
just tried to use-package, it always failed to launch,
so i want to add the config to .emacs dirrectly

**Comment by yuchen-lea** [comment]
just set the variables, here's my config:
```
  (setq org-brain-path "~/Documents/Notes/")
  (setq org-id-track-globally t)
  (setq org-id-locations-file "~/.emacs.d/.org-id-locations")
  (setq org-brain-visualize-default-choices 'all)
  (setq org-brain-title-max-length 12)
```

**Comment by Kungsgeten** [comment]
Have you installed the package? Which version of org-mode and Emacs are you using? Have you tried adding `(require 'org-brain)` to your init? What do you get and how do you try to launch `org-brain`?

**Comment by longlu** [comment]
emacs 26.1 x86_64  mingw32.

latest version.

i changed the settings thru   'cusomize group GUI setting'
that way it worked.

for this tho:

;;For Evil users
;;(with-eval-after-load 'evil
;;(evil-set-initial-state 'org-brain-visualize-mode 'emacs))


there's not such seting on this in customized group.

**Comment by Kungsgeten** [comment]
Closing this since I don't think installation guides is needed in the README. There's other tutorials on general package managment and installation in Emacs.
