### ISSUE TITLE
org-brain-headline-to-file Doesn't Update the Metadata of Pinned Entries

### ISSUE THREAD

**Issue by delaanthonio** [Kungsgeten/org-brain#141]
If you have a _pinned_ headline entry, and you convert the headline entry to a file with `org-brain-headline-to-file`, then it becomes impossible to open with `org-brain-visualize` since it the metadata for the pinned entry wasn't updated by `org-brain-headline-to-file`. Org-brain will complain that it cannot find the entry. One workaround is to unpin the headline entry that you want to convert to a file and repin it afterwards. Ideally, `org-brain-headline-to-file` should update the metadata of the entry if it's pinned.

**Comment by Kungsgeten** [comment]
Thanks for reporting this! It should work now with the latest commit.
