### ISSUE TITLE
Properties drawer leaking into Entry

### ISSUE THREAD

**Issue by srgkoshelev** [Kungsgeten/org-brain#142]
I have played around with the org-brain, including an attempted and apparently successful attempt of changing child file into child heading. After that some odd behavior ensued that forced me to purge /brain. Unfortunately, one issue persists.

Issue:
After creating a first child header its PROPERTIES gets shown as parent's Entry in visualization mode:
<img width="692" alt="screenshot 2019-01-05 21 35 09" src="https://user-images.githubusercontent.com/7409194/50731742-dcfabb80-1131-11e9-9691-d92b42701e8d.png">

Workaround:
It seems that adding an empty line at the start of the file helps:
<img width="692" alt="screenshot 2019-01-05 21 36 44" src="https://user-images.githubusercontent.com/7409194/50731745-061b4c00-1132-11e9-8383-3035aef215db.png">

I am not sure whether my previous actions have caused it. If so it would be nice how to reinstate a clean slate.

I forgot to add, I am using Spacemacs, 0.300.0@26.1 (spacemacs) on Mac.

**Comment by Kungsgeten** [comment]
Hi! I tried to create a new file and couldn't recreate this. I do not see the property drawer as entry text.

**Comment by facelesspanda** [comment]
managed to reproduce it on a bare install.
![image](https://user-images.githubusercontent.com/13928490/56397445-0accc180-6244-11e9-94f5-5a6c6fb021e9.png)


The config is this:
```elisp

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(eval-when-compile
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
  (require 'use-package))
(use-package org-brain :ensure t
  :init
  (setq org-brain-path "directory/path/where-i-want-org-brain")
  ;; For Evil users
  (with-eval-after-load 'evil
    (evil-set-initial-state 'org-brain-visualize-mode 'emacs))
  :config
  (setq org-id-track-globally t)
  (setq org-id-locations-file "~/.emacs.d/.org-id-locations")
  (push '("b" "Brain" plain (function org-brain-goto-end)
          "* %i%?" :empty-lines 1)
        org-capture-templates)
  (setq org-brain-visualize-default-choices 'all)
  (setq org-brain-title-max-length 12))
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (org-brain use-package))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

I'm a spacemacs user too so this I had to find some weird GUI way to install use-package.
I literally copied the readme file's example config and then used `org-brain-switch-brain` to change the brain-path.

So this is not an issue with spacemacs. @srgkoshelev you can close your issue there I think.

Emacs version is 26.2
org-brain version installed from melpa is 20190305.1416

**Comment by Kungsgeten** [comment]
I've made a commit #193 which may affect this issue. @facelesspanda could you please try again with the latest version?

**Comment by facelesspanda** [comment]
sure, I'll let you know when I get home tonight.

**Comment by Kungsgeten** [comment]
@facelesspanda @srgkoshelev Do you know if you still get this error?

**Comment by facelesspanda** [comment]
Ah dang totally forgot about this! Lemme check real quick.


.......
turns out It's not "real quick" at all; you updated the dependency to org 9.2 and I suck so much at vanilla emacs that I can't manage to update it (my builtin is 9.1.x)

When using my Spacemacs on develop branch, though, no issues

**Comment by facelesspanda** [comment]
there's an Emacs update to do haha. going from version 26.2 to 26.3. Built-in probably changed.

**Comment by facelesspanda** [comment]
Can confirm issue is absent on 26.3 with org-9.2.5 and latest org-brain (used the exact same setup from above)

**Comment by Kungsgeten** [comment]
@facelesspanda I'm on org-mode 9.2.3 at the moment, and here `org-capture-templates` still exist. Hmm... I'll have to check with the latest version. Anyway I've closed this since it seems to be fixed.
