### ISSUE TITLE
Move heading child between parents

### ISSUE THREAD

**Issue by srgkoshelev** [Kungsgeten/org-brain#144]
Hi Kungsgeten!

Thank you again for your great work!

One thing that I noticed is that a parent of heading child can't easily be changed save for editing the file. Say, I have a heading child that I want to move to a different parent. I add a new parent but when I try to delete the original parent - it is not shown in the list, so I have to manually move the subtree.

Is there a way this could be implemented?

Thank you!

**Comment by Kungsgeten** [comment]
If I understand correctly you want to move an entry so that it gets a different "local" parent? It sounds like it could be useful. I'll see what I can do :)

**Comment by srgkoshelev** [comment]
Yes, this is correct. (If "local" means heading one level higher)

Thank you very much!

**Comment by Kungsgeten** [comment]
I've sort of fixed this now. You can use `org-brain-refile` (bound to `C-c C-w`) when visualizing. This will move/refile the visualized entry to another parent. The bad news is that since it is using `org-refile` it can not move file entries, and it can not choose a file entry as a new parent.

**Comment by Kungsgeten** [comment]
#221

**Comment by Kungsgeten** [comment]
This functionality has now been added. You can use `M p` when visualizing to `M`ove to another `p`arent.
