### ISSUE TITLE
Limit random and wander to childs of a parent

### ISSUE THREAD

**Issue by rosetree** [Kungsgeten/org-brain#145]
My scenario: as a student I have notes for different courses in the same brain (since they overlap sometimes and it’s great to connect friends). The courses are top-level parents for their contents. Now when learning, I’d like to have random topics coming up, but limited to a specific course.

It would be great to limit `org-brain-visualize-random` (or `w`) to a single parent. Maybe by setting a variable or a tag on the regarding subtree or for a session (whatever that could be).

**Comment by Kungsgeten** [comment]
I don't use the random feature much myself, but I could see this being useful. Its pretty easy to implement if you only want direct children as "targets", but I guess you'd want children as well as grandchildren to the parent?

**Comment by rosetree** [comment]
You’re right, I’d like to target every entry, that has the marked
parent somewhere in its parent hierarchy. I can see that there are
some challenges. Especially as I mean any subtrees as well as linked
parents in the property entries.

**Comment by Kungsgeten** [comment]
There's currently a function which can get an entry's children, but not grandchildren and even further down. I guess this would be possible to do though. A potential problem is if there's a loop somewhere (which `org-brain` allows), for instance A -> B -> C -> A.

**Comment by rosetree** [comment]
As far as I can tell, this might be solved with a modified version of Dijkstra’s algorithm, where the distance is removed. Below are some pseudo-code style notes. I hope it’s clear what I meant, if not feel free to ask. What do you think? Could this work?

### entry-successors (start-entry)
- _marked-entries_ : a list of entries that are within reach of the _start-entry_ (including _start-entry_)
- _checked-entries_ : a list of reachable entries whose children have been marked

1) add _start-entry_ to _marked-entries_
2) from all entries take one entry _e_ with _e_ not in _checked-entries_
3) add _e_ to _checked-entries_
4) for every child _c_ of _e_ that is not in _marked-entries_:<br>add _c_ to _marked-entries_
5) repeat with 2. until there’s no entry in _marked-entries_, that isn’t also in _checked-entries_

**Comment by Kungsgeten** [comment]
It is now possible to wander among "descendants" by using the universal prefix (`C-u`) when using random/wander from the visualize interface. For instance `C-u W` would do what you ask for in this issue :)

**Comment by rosetree** [comment]
Works! Thank you :)
