### ISSUE TITLE
org-mind-map-write for org-brain?

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/org-brain#147]
There is org-mind-map-write which can create png/pdf/svg mind maps from org-mode files. Would it be possible to create such mind maps from org-brain itself, e.g. starting from current entry/thought in the center, then adding all links up to a given distance, which could be specified by the user.

org-brain-mind-map-write
How many steps? User would answer: 7
Which format? User would answer: pdf/svg/png

**Comment by Kungsgeten** [comment]
Maybe, I haven't used that function myself.

**Comment by michaelsjackson** [comment]
It's data based approach, using opml, would allow immediate import into freeplane for example. Not sure if opml standard has any limitations on org-brain concept with multiple parents, children, friends of current thought.

**Comment by theottm** [comment]
I would also be very interested in such a feature. I would like to try to implement it.
I guess "all there is to do" is to get the data from the brain graph (nodes and edges of the brain) as a lisp object (as an adjency matrix or similar) and then plug it into org-mind-map or directly use opml.
Is there a simple function that would give back  such a lisp object ?

**Comment by theottm** [comment]
Oh apparently it has already been done here #105

**Comment by Kungsgeten** [comment]
@theottm There's no built in function to do exactly what you ask, but its not very hard to write one. What would the input data be (single entry or the whole brain), and how would you like the output data to be represented?

Here's a simple example to get a structure from the org-brain entry at point:

```
(defun org-brain-structure ()
  (let ((entry (org-brain-entry-at-pt)))
    `(:title
      ,(org-brain-title entry)
      :parents
      ,(mapcar #'org-brain-title
               (org-brain-parents entry))
      :children
      ,(mapcar #'org-brain-title
               (org-brain-children entry))
      :friends
      ,(mapcar #'org-brain-title
               (org-brain-friends entry))
      :resources
      ,(org-brain-resources entry))))
```

**Comment by theottm** [comment]
Oh nice, this is exactly the type of function I was talking about. I'll play around with this and come back if I have some questions :)

From what I can foresee now, I think I would want to have a recursive version of that function, preferably in a breadth-first fashion, with adjustable number of iteration. That way I could get the "near environment" from a node. And eventually setting the limit of iteration to none would give the whole graph. 

I think this joins the discussion in #226 about having a simple query language. I guess making this kind of function public would be a great foundation for further hacking. But maybe org-brain-entry-at-pt is actually already enough. I need to play a bit more around before I can tell.

**Comment by Kungsgeten** [comment]
I've started a new repository named [org-brain-export](https://github.com/Kungsgeten/org-brain-export). I think discussions focused on exporting could be moved there. A starting point could be: https://github.com/Kungsgeten/org-brain-export/issues/2

I'm closing this since I think export discussions could take place there.
