### ISSUE TITLE
org-wiki and org-brain can be used in parallel

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/org-brain#151]
I like the fact org-brain and org-wiki do not disturb each other, so you can use both in parallel, or together. Concept links you can build up in org-brain, but sometimes, if you just want to add a few more detailing links, you could use only org-wiki instead, without adding any parent,child,friend links in org-brain, keeping its view simpler, not overcrowding the entries there. Just wanted to share this thought here.

**Comment by Kungsgeten** [comment]
Hi! Glad that this works for you! I don't really understand the workflow, but if you describe it better I could perhaps add information about it in the README.

**Comment by michaelsjackson** [comment]
The workflow is simple. The idea is not adding all detail links into org-brain, instead linking these details via org-wiki, from the .org files. So anyone decides while linking if that linking is too detailed or not. If more general, linking goes into org-brain, too much detail then adding instead into org-wiki. Where this decision border will be is user dependent. I just liked the fact this is possible, which is great. This feature we have already for free. You only need to install and use org-wiki additionally. No need to exclude it completely.

**Comment by Kungsgeten** [comment]
Closing this since org-wiki is mentioned already in the README. If some special kind of use case should be mentioned, please submit a pull request.
