### ISSUE TITLE
multiple org-brain-path paths?

### ISSUE THREAD

**Issue by FirstLoveLife** [Kungsgeten/org-brain#152]
I have multiple fold for brain files:

1. ~/brain/: `(setq org-brain-path "~/brain")` ;;the default fold, for computer science stuff
2. ~/NOLPOE/  ;; for law notes

I hope if I'm in ~/NOLPOE/, org-brain-new-child can create child file locally(also in ~/NOLPOE/), instead ~/brain/, how to achieve this effect?

**Comment by Kungsgeten** [comment]
If I understand correctly you should be able to use `M-x org-brain-switch-brain` in order to choose NOLPOE as your new directory.
