### ISSUE TITLE
Open org-noter from visualized brain entries

### ISSUE THREAD

**Issue by rosetree** [Kungsgeten/org-brain#154]
Recently I combined this great package with the [`org-noter` document annotator](https://github.com/weirdNox/org-noter). This works admirably well out of the box. There are just few small issues, that can be improved. The first being that `org-noter` doesn’t add IDs to new notes (see this issue: weirdNox/org-noter#62).

The second: it’s not possible to call `org-noter` on an visualized entry of `org-brain`. This can be manually done with opening the current entry and `M-x org-noter` there. But this is kind of slow. The following function opens an `org-noter` session from a visualized entry and add this to `C-c n` in the visualize mode.

``` elisp
(defun mdr/org-brain-open-org-noter (entry)
  "Open `org-noter' on the ENTRY.
If run interactively, get ENTRY from context."
  (interactive (list (org-brain-entry-at-pt)))
  (org-with-point-at (org-brain-entry-marker entry)
    (org-noter)))

(define-key org-brain-visualize-mode-map (kbd "\C-c n") 'mdr/org-brain-open-org-noter)
```

Partly sharing this for reference here, in case anyone searches for something similar. Not sure if this should be added in the readme file to the “Other useful packages” section, though. Also I’m happy to here, if there’s something that could be improved.

**Comment by Kungsgeten** [comment]
This is cool and seems helpful! I haven't used `org-noter` myself so I feel a bit reluctant to put it in the README before trying it. I'm mostly on a Windows system, and I haven't gotten pdf-tools to work there. I'll try to remember to test it though when I'm using my Linux machine.

**Comment by rosetree** [comment]
I agree, trying first seems reasonable. The above mentioned issue with `org-noter` got resolved recently. The following line makes sure, that `org-noter` creates IDs on new headlines; so new notes are automatically shown in the brain.

``` elisp
(add-hook 'org-noter-insert-heading-hook #'org-id-get-create)
```

Oh and btw: `org-noter` doesn’t require `pdf-tools`. The Emacs DocView mode is enough – if that works on your Windows machine.

**Comment by dangom** [comment]
@rosetree your setup seems really cool. Do you have your config somewhere, or a description of your workflow? Would be interested to hear more about how you use org-brain for keeping notes.

**Comment by rosetree** [comment]
@dangom Thanks for your interest. I currently don’t have my config published and I haven’t written about my workflow, yet. One reason is, that I only use it for a month… I plan to write about it, when I have some time to do so.

However, the config is pretty basic: I use the snippet from the `org-brain` readme file and the code in this issue.

A short overview of the workflow: I currently create an `org-brain` headline for every topic of a lecture, call `org-noter` on that headline, use the PDF file of the presentation the profs send us before and then I follow along, taking notes on the slides while they talk. Later I link those entries in the visualized brain. I hope that gets you an idea of the process.

**Comment by michaelsjackson** [comment]
@rosetree Do you have a video of this workflow? If not yet, in future maybe?

**Comment by rosetree** [comment]
@michaelsjackson unfortunately there is no video of my workflow, yet. But it’s a good idea to add a video, if I’m going to write about this workflow.

**Comment by Kungsgeten** [comment]
Sorry for taking so long, but I've now tried `org-noter` and your command seems to work great! I've added it to the README.

**Comment by rosetree** [comment]
Thanks, for giving it a try, @Kungsgeten

**Comment by bepolymathe** [comment]
Hi,

Just a comment. There is a mistake in the README. You need to add un "#" character like this

` (define-key org-brain-visualize-mode-map (kbd "\C-c n") #'org-brain-open-org-noter)`

**Comment by rosetree** [comment]
@michaelsjackson and @dangom I just published a [blog post about my setup and my workflow](https://plasisent.org/2019/lecture-notes-with-emacs-org-brain-noter/). This also includes a short video. I hope you find this still helpful. Sorry that this took so long.

**Comment by Kungsgeten** [comment]
@rosetree Great! Do you mind if I link to it from the README?

**Comment by rosetree** [comment]
Glad you like it, @Kungsgeten. I don’t mind at all; I’m happy if it helps more people.

**Comment by dangom** [comment]
Hey, just wanted to say this is really awesome! Thank you for taking the time to put this together and to share it. 
The idea of using noter to add notes to pdf slides is also quite cool. Thanks for that as well!
