### ISSUE TITLE
Prefix for filenames

### ISSUE THREAD

**Issue by DynamicMetaFlow** [Kungsgeten/org-brain#155]
Greetings, thank you for creating and maintaining org-brain. I'm using org-brain to implement a note-taking system called [zettelkasten](https://zettelkasten.de/posts/overview/).

In this system, the filename of a note is recommended to start with a unique id based on the time and the date, for example: "2018-07-09-2115 This is a note.org."

Would it be possible that when adding a thought using org-brain-add-child a prefix could be defined to be appended to the filename, "%Y-%m-%d-%H%M"?

Thank you for your time and consideration.

**Comment by Kungsgeten** [comment]
Hi! With the current functionality that would be problematic, unfortunately. The function that creates files doesn't really care if there already is a file or not, so we'd have to create a check to see if the file is new and then rename it.

**Comment by Kungsgeten** [comment]
I just realized, when looking at the function which creates new file entries, that a prefix like this wouldn't be that hard to add. The question would be if its necessary/needed, and if so how the configuration should work.

I'm a bit sceptic since org-mode already provides features to time-tag stuff, although perhaps not files in general.

**Comment by MarioRicalde** [comment]
There has been no follow up from the original creator of this issue post your response @Kungsgeten - perhaps it's time to close it?

Cheers.

**Comment by Kungsgeten** [comment]
@MarioRicalde @DynamicMetaFlow Yes, I think its time to close this. Its not something I think that `org-brain` needs to provide. You could get a visual indication of the timestamp creation by configuring how entry titles are visualized.
