### ISSUE TITLE
Linking between org-brain's?

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/org-brain#157]
Is it already possible to link between multiple different org-brains? Clicking on a org-brain-link would switch to another org-brain, loading that entry there, thus showing the new visualization, having automatic-backlinks would allow easy backjumping. Thus jumping between org-brains. It might help separating content and not having too many entries per org-brain. For lecture scenario, I guess this is a useful organization technique. If everything is in a single org-brain, over time you might not have a good overview what is where, what is not necessary here and so on. Separating org-brain's is best I guess.

The idea would be using each org-brain for a lecture. org-brain would be then only a visual helper/guide to organize the content, which would be spread to multiple .org files, of course. 

The idea I got from trying out vym (view your mind), another promising mindmapping tool, where you can create multiple mindmaps. 

Then later, why not also directly converting the org-brain structure into a format which can be imported into vym. So you could continue in vym if wanted so. vym can open any xml files, including freemind and mind manager. vym can export even more file formats: Most notably, .org files.

Having a useful org-brain to vym roundtrip could be useful, wanted to share this aspect quickly here.

**Comment by Kungsgeten** [comment]
Hi!

At the moment you can ofcourse create a normal link to another org-file, in another brain. That won't switch the brain (change the variable holding the brain path) though. I guess that it could be possible to implement, but then you'd have to specify the full path to the root of the brain you're switching to.

**Comment by michaelsjackson** [comment]
Another solution could be using subdirectories, relatively to org-brain path.

Example: org-brain-path:  ~/org-brain
Org-brain switching link could be: /week1/concept_a.org, this would switch to new ~/org-brain/week1 org-brain. Not sure is using relative links for org-brain-path is a good thing or not, but worth a try maybe? It would keep the linking process minimal at least.

**Comment by Kungsgeten** [comment]
At the moment org-file can already be in sub-directories, as a way to
organize your files.

**Comment by michaelsjackson** [comment]
But will those subdirectories be used as separate org-brain-visualizations, not containing the rest in other subdirectories? I guess, no. A setting doing just that, could be useful.

**Comment by Kungsgeten** [comment]
I coded this as a quick test. Would you mind trying it out? Add it to your init-file.

```
(defun org-brain-switch-link-complete ()
  (concat "brainswitch:" (read-directory-name "Brain dir: " org-brain-path)
          "::"
          (read-string "Entry: " "index")))

(defun org-brain-switch-and-visualize (directory entry)
  (org-brain-switch-brain directory)
  (org-brain-visualize entry))

(defun org-brain-switch-link-follow (link)
  (let ((link-parts (split-string link "::")))
    (org-brain-switch-and-visualize (car link-parts)
                                    (cadr link-parts))))

(org-link-set-parameters "brainswitch"
                         :complete 'org-brain-switch-link-complete
                         :follow 'org-brain-switch-link-follow)
```

Now if you open an entry in org-mode, you can add a link (using `C-c C-l` by default) with the `brainswitch:` prefix. This lets you choose the path of the brain, and the name of an entry in that brain (this version will only work with file entries).

The link should show up as a resource when you visualize. Please try it out and see if its similar to what you request.

**Comment by michaelsjackson** [comment]
Thanks for the quick implementation, seems to work, will test it more in the next days, can report back my experiences then.

**Comment by Kungsgeten** [comment]
I've added the `brainswitch` link to the package. The completion has been improved, so that it will prompt for an entry in the brain you're creating the link to.
