### ISSUE TITLE
Automatic switching to subdir brain of opened .org file

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/org-brain#158]
Now where we have, inofficially yet, subdir brain switching, would it be possible org-brain does this brainswitching automatically?

Example:  org-brain path:  ~/org-brain
Subdirs: 
/week1/concept_a.org
/week2/concept_b.org

If I open concept_b.org, it should auto-switch to week2 brain. Same for concept_a.org and week1. org-brain would just look in which subdir the .org file is, and switch to that sub-brain, having the advantage you can immediately get the correct, minimal, brain visualization.

You could just organize your data in subdirectories, and the rest org-brain would handle automatically.

**Comment by Kungsgeten** [comment]
The problem is that the subdirectories is part of the brain. It works recursively through the directories in the root.

**Comment by michaelsjackson** [comment]
I see, but there could be a switch command, changing that behaviour to local/non-recursive mode. e.g. for lecture cases you could switch into that 'minor mode', getting your minimal brain visualizations, in rest cases you could switch back to current global/recursive mode. Something like:
org-brain-non-recursive-mode   or org-brain-local-mode
org-brain-recursive-mode  or org-brain-global-mode

**Comment by Kungsgeten** [comment]
`org-brain` will now automatically switch brain like you describe if there's a "brain datafile" in the current directory when running `org-brain-visualize`. The easiest way to create such a datafile is to run `M-x org-brain-switch-brain` one time, which will create the datafile.

You can also make `org-brain` scanning non-recursive by setting `org-brain-scan-directories-recursively` to `nil`.

**Comment by michaelsjackson** [comment]
Sounds great, thanks a lot!
