### ISSUE TITLE
Annotated relationships?

### ISSUE THREAD

**Issue by shlevy** [Kungsgeten/org-brain#160]
I'm new to the brain/mind mapping style tools, so perhaps this wouldn't actually be useful, but reading through the documentation I was wondering if it might make sense to let users annotate the relationships between entries beyond just the 3 parent/child/friend categories.

As an example, my initial use case for looking into org-brain is to capture the important researchers, articles, journals, institutions, conferences, etc. within a given academic field, and the relationships between them. I might want friend relationships between two researchers who collaborate a lot as well as friend relationships between two researchers who dispute each other a lot, and I can imagine wanting to see on-screen (e.g. through some text above the line connecting them or font colors or something) some notation that distinguishes the two kind of "friends".

Would this be feasible? Valuable?

**Comment by Kungsgeten** [comment]
Hi! Sure, I think it would be useful. The main problem would probably be the implementation part of making it look nice in Emacs :)

**Comment by shlevy** [comment]
I can imagine some visualization options:

* Coloring the lines/arrow heads
* Symbols in the lines
* Text above/inside the lines (would need to be short)
* Commands to filter which relationships are visible by type
* Grouping e.g. children of type foo on one side and children of type bar on another, possibly with some persistent preference per relationship type
* Tooltips above the lines

**Comment by spacekitteh** [comment]
This is probably my biggest wish for org-brain. Something like RDF annotations.

**Comment by Kungsgeten** [comment]
It is now possible to annotate edges. Just press `e` when hovering over the relationship you want to annotate. By default the annotation goes in both directions, but if you want it one-way you can use `C-u e` instead. Annotated relationships have a separate face (well, a box around the entry by default).

In order to read the annotation you can hover over it with the mouse, or place the point on it and it will show up in the mini-buffer.

**Comment by shlevy** [comment]
Awesome, thanks!
