### ISSUE TITLE
Using Helm multiple candidates selection in a relationship only take the last candidate 

### ISSUE THREAD

**Issue by techapu** [Kungsgeten/org-brain#161]
Hi! Your package is incredible useful for my org workflow, thanks! I'm a recent but heavy user by now. I've switched from thebrain.com because their lack of integration with emacs. 
One issue I need to solve is that org-brain-choose-entries doesn't play well with Helm multiple-completing-read. 
I'm not a professional programmer so I can understand the code in a superficial way but not implement my own code yet, even when I am learning a lot to do so in the future.
So I ask you for help with this issue: I need to select multiple candidates in helm, and make the org-brain-add-parent child friend etc. take the candidates as when I select one by one with the ";" separator. I have a lot of headlines and nodes so I need Helm or Ido to match, narrow and select.
Thanks!

**Comment by techapu** [comment]
After thought: Maybe a workaround can be achieved from your helm-org-brain-rifle function. I use that function. It's a little slower than helm-org-rifle in my emacs. But helm-org-rifle has more actions on candidates predefined than the helm default (sole completion). By example, pressing f5 one can refile directly from the helm buffer without opening the file and executing the function after thet, and then returning to the original buffer.
 I wonder if I could have the option to add parent, child etc as a helm action over the candidate heading in helm-org-brain-rifle.. But I don't know yet how to create custom actions in helm, if it is possible. Sadly I notice that this workaround would be faster than the present defaults, but not fulfill the multiple candidates issue I opened previously.

**Comment by Kungsgeten** [comment]
Hi! I've used Helm and made some stuff with it, but I'm not using it at the moment. I don't know if there's an easy way to add support for multiple selections in Helm when you're using at as your default selection engine. Helm is a popular package though, so it would be nice to support it somehow.

**Comment by techapu** [comment]
Hi! Days pass by and I'm trying to make my way to how to do it. 
I'm stuck with the syntax of my elisp. May I ask you for help? Sorry for the noob aproach.
By example the definition of custom actions in helm-org-rifle is a code like this in my emacs.

`(helm-org-rifle-actions`
   `(quote`
`    (("Show entry" . helm-org-rifle--show-candidates)`
`     ("Show entry in indirect buffer" . helm-org-rifle-show-entry-in-indirect-buffer)`
   `  ("Show entry in real buffer" . helm-org-rifle-show-entry-in-real-buffer)`
 `    ("Clock in" . helm-org-rifle--clock-in)`
`     ("Refile" . helm-org-rifle--refile)`
`     ("Add brain parent" . [...])`
`     ("Add brain child" . [...])`
`     ("Add brain child headline" . [...])`
`     ("Add brain friendship" . [...]))`
`     ))))`

And then there is a code for each function, with a `(candidate)` argument.

It seems to be easy to add the needed functions to make the multiple candidates completing-read work. But I can't figure out how to call the org-brain functions in a non interactive way. `org-brain-add-child` by example, is an interactive function an takes the entry at point. How can I create a thougth programatically, with a lisp expression? I mean giving the function an argument.

I tried to create the custom functions to the last entries (the org-brain ones) without luck. I tried to call that functions from eshell and from scratch to test, and only works when I call them from the mini-buffer. What I am doing wrong? It gives me an error like "wrong number of arguments" .
I tried diferent formats, with a lambda, with a lambda and interactive function, with function and I can't figure out how to call, by example, `org-add-child-headline` from elisp code.
Can you help me? If I figure out this I can make the needed functions for this feature to work.

In the meanwhile, I'm happy because I discovered a ugly workaround to this issue: Calling  `org-brain-goto-end` function then selecting multiple candidates on helm buffer, and pressing `C-c C-i`. Then Helm inserts the multiple candidates headings on the correct way in the current buffer (remember that helms don't use the minibuffer but it's own buffers and that maybe part of the issue). So I need to be in a clear space, by example a brand new buffer so I put many candidates there. Then with a macro I glue every candidate with the `;`separator. Then I kill that chunk, and calling by example `org-brain-add-friendship` can yank all that perfectly formated argument with the multiple candidates that the function expects. You may doubt it but even all this ugly workaround saves me thinking time when working, because the number of my nodes is high so when I call the functions without a narrower and selector like helm, with the default org-brain configuration it takes a lot of pain to find each node I want to connect.

Thanks in advance! Sorry for the long entry....

**Comment by Kungsgeten** [comment]
I'm no Helm expert (though I wrote a fairly complicated package using it, but I haven't used it since that). I think though that in order to do what you want (if I understand correctly) you'd need to define a new Helm function, with actions and stuff. This is similar to what you suggest.

Perhaps there's a better way to do this, but here's my go at creating a Helm function for `org-brain`:

```
(defun helm-brain-add-children (_c)
  (dolist (candidate (helm-marked-candidates))
    (org-brain-add-relationship (org-brain-entry-at-pt) candidate))
  (org-brain--revert-if-visualizing))

(defun helm-brain-add-parents (_c)
  (dolist (candidate (helm-marked-candidates))
    (org-brain-add-relationship candidate (org-brain-entry-at-pt)))
  (org-brain--revert-if-visualizing))

(defun helm-brain-add-friends (_c)
  (dolist (candidate (helm-marked-candidates))
    (org-brain--internal-add-friendship (org-brain-entry-at-pt) candidate))
  (org-brain--revert-if-visualizing))

(defun helm-brain-delete-entries (_c)
  (dolist (candidate (helm-marked-candidates))
    (org-brain-delete-entry candidate)))

(defun helm-brain-archive (_c)
  (dolist (candidate (helm-marked-candidates))
    (org-brain-archive candidate)))

(defvar helm-brain-actions
  (helm-make-actions
   "Visualize" 'org-brain-visualize
   "Add children" 'helm-brain-add-children
   "Add parents" 'helm-brain-add-parents
   "Add friends" 'helm-brain-add-friends
   "Delete" 'helm-brain-delete-entries
   "Archive" 'helm-brain-archive))

(defun helm-source--brain ()
  (helm-build-sync-source "Brain"
    :candidates (mapcar (lambda (x)
                          (cons (org-brain-entry-name x)
                                (if (org-brain-filep x)
                                    x
                                  (nth 2 x))))
                        (append (org-brain-files t) (org-brain-headline-entries)))
    :action 'helm-brain-actions))

(defun org-brain-helm ()
  (interactive)
  (helm :sources (helm-source--brain)))
```

Now the command `org-brain-helm` can be used to visualize an entry. You can also use it to add parents/children/friends, delete entries, and archive entries. Multiple candidates are supported (except for visualizing). One thing that I couldn't quite understand how to do, was to get the choice if you enter some text which isn't a candidate (this would be useful for creating new entries in org-brain).

Anyway please try it out and let me know what you think. If you find it useful, I can clean up the code and add it to the main repository.

**Comment by techapu** [comment]
Thanks Kungsgeten for the fast answer! The code is very elaborated!
It has some bugs in the functions, I'll try to enumerate.

1. When I used the visualize function of org-brain-helm, instead of taking me to the thought I was prompted, it showed me a barebones *org-brain* buffer with only the ID of the headline input as if it were the title of the thougth. Curiously, when I pressed "o" it went to the correct headline of the thougt. And when I called `org-brain-visualize-entry-at-pt` went accurately to the thought in the, let's say, plex.

2. When I used the `org-brain-add-friendship`, it kind of worked, I mean it created the friendships but erased the headline from the org-brain datas. This is the output in the *Messages* buffer:

> org-brain-replace-links-with-visible-parts: Wrong type argument: stringp, nil
(New file)
Saving file /home/techapu/org/Brains/1dd234d7-0d72-40d7-baa1-94e76fe637fc.org...

So it created a new org file but with the headline id as title. It exists in my org dir now. And in my original org file I can see the headline complete, ok, with the parents and the friends ids, and contents, but if I call `org-brain-visualize-entry-at-pt` it outputs a wrong type argument error. And the plex is almost empty, only shows the thought friends but no thougts in the middle nor parents. In the "mindmap" view is enterely empty. 

Back to the moment of the friendship input, the next thing was a prompt message displayed:

> Non-existent agenda file ~/org/Brains/1dd234d7-0d72-40d7-baa1-94e76fe637fc.org.  [R]emove from list or [A]bort?
I aborted. 

Then scanned for IDs 19 files. 

3. When I tried the `org-brain-add-parents ` it added the parents, and in this case I can return correctly to the thought. But also created id named org files, and returned the same non-existent agenda file error. The difference after that is that saved all Org buffers after that, but increased the number of ID named org files scanned from 19 to 34. I was adding three candidates as parents of the thougth at point in the plex. 
Another difference is that I can access this thougth with `org-brain-visualize-entry-at-pt`. So it kind of returned me a working output, even with the bugs. 
Remember that the add-friendship function broke the thought. 

I didn't tried the other options. 

Thanks for the brave work! I don't know how to help with this issues. 
If it is of use, I can paste all the message output. Ask me whatever you need.

**Comment by Kungsgeten** [comment]
Aah, it didn't work with headline entries. Try to replace the `helm-source--brain` function with this instead:

```
(defun helm-source--brain ()
  (helm-build-sync-source "Brain"
    :candidates (mapcar (lambda (x)
                          (cons (org-brain-entry-name x) x))
                        (append (org-brain-files t) (org-brain-headline-entries)))
    :action 'helm-brain-actions))
```

**Comment by techapu** [comment]
That worked! Thanks, it's a helm source org-brain specific! Congrats.
I didn't try the archive function because I don't use that. But if you want I archive something to make it a more complete test. What other thing do you need to make this a ready feature, how can I help?

I'm more than happy with the helm functions. It will boost me a lot.

I suggest you that this functions, well documented, may represent a big leap ahead from the state of the package right now. I mean, some functions like this, but outside Helm. You see, when I have a big document, with a lot of headings, and I want to create relationships with other entries with code instead of manual one by one, I found that your package has a more manual oriented behaviour (maybe I'm wrong and don't understand well how to use it). But I think it can be easy for you to make the functions also ready to be evalued from elisp code by other packages or custom elisp from a user, in a way we could make scripts to create automated relationships, so we can save time and effort. It could add some extensibility to the package, and make it even greater.
I work with law texts, and pdf of theory, and legal cases. So sometimes I need to create relationships from the doctrine texts to the legislation in a prefixed way. Every time it cites a particular law, I want to have that law as a friend of the heading I'm working, this is a raw and simple example. Every time the text refers to an author or a book, I may want to have it related with a relationship. Or to make a fast glosary, I want to create a friend to the heading (the definition of the concept), and that this friend has a particular parent (the glosary cathegory). If we can make macros or code with your functions this kind of behaviour would be more accesible to the medium user.

**Comment by techapu** [comment]
I don't know how you have to name the functions, but they are functions to make relationships between previously created thoughts. So maybe add parent, add friend, add children, looks ambiguous. Add relationship maybe looks better.
Thanks again!

**Comment by Kungsgeten** [comment]
I don't use archiving much myself, but I can test it to see if it works. You don't really have to do anything. I could either add the helm function to `org-brain` itself, or maybe just in the README. I really don't want to add Helm as a dependency, but perhaps it could be an optional thing.

I'm not sure I understand your latest suggestion. Are you saying that the `org-brain` "API" should be more hackable? I'm very interested if you have ideas on what kind of functions that should be added, but there's already quite a bit there. The documentation for it would have to be read inside of Emacs though, and some functions could probably be better named.

I think the examples you give would be possible to hack together if you're comfortable with elisp. The difficulty may be to get the correct "entry ID" to the entries you want to use, since that can be hard to do from code.

**Comment by Kungsgeten** [comment]
Helm (and Ivy) support has now  been added. `M-x helm-brain`
