### ISSUE TITLE
Bulk edits with TheBrain style "selection"?

### ISSUE THREAD

**Issue by gmenzel** [Kungsgeten/org-brain#167]
Hi @Kungsgeten — this is a great project! Thanks for all your work!

TheBrain allows you to select a group of nodes, both manually and via a search, and then perform bulk operations on them such as adding them as children, parents, or friends of another node, unlinking them from another node, etc. I would find this immensely helpful in `org-brain`. Would you consider implementing such functionality?

**Comment by Kungsgeten** [comment]
Hi! Thank you for the kind words. I think your suggestion might be similar to what PR #168 is trying to do. I'm abroad at the moment, but I'll check it out when I get back home at the end of the month.

**Comment by Kungsgeten** [comment]
Thanks to @drbronner it is now possible to select entries and operate on them. See the README for details. If you want to search for entries in this way, and select them for later operations, you can use the `helm` or `ivy` integration.

**Comment by gmenzel** [comment]
Ah actually @drbronner is my other github account — sorry for the confusion!
