### ISSUE TITLE
Opening up children's resources

### ISSUE THREAD

**Issue by bepolymathe** [Kungsgeten/org-brain#169]
First of all, thank you for this work. It's very useful and I'm imagining a lot of use ;-)

Currently, the shortcut "r" calls the command "org-brain-open-resource". The latter proposes to open the resources attached to an entry. For children it is very useful. But could you imagine if calling this command would also show the children's resources when you are on a parent entry ?

![image](https://user-images.githubusercontent.com/29939805/60764364-bab60c00-a088-11e9-825e-2d21ae5a0cfb.png)

In your main example, calling "org-brain-open-resource" on the "programming" entry would open the resources of "Python", "Programming books" and "Emacs".

What do you think of this idea?

**Comment by Kungsgeten** [comment]
I don't think it would be very hard to implement. Should it only choose one level down (its own and its children's resources) or also all grandchildren, grand-grandchildren, etc?

**Comment by bepolymathe** [comment]
Good news... and good question. In my use, the lower levels would be sufficient, but I think it would be a good idea to have access to grandparents in some cases.

**Comment by Kungsgeten** [comment]
Now `C-u r` when visualizing lets you choose resources from the entry and its descendants. I think that should be okay? Please let me know what you think :)

**Comment by bepolymathe** [comment]
Ok, great. It works for me. 
Thanks ;-)

**Comment by Kungsgeten** [comment]
#138
