### ISSUE TITLE
Link integration problem 

### ISSUE THREAD

**Issue by bepolymathe** [Kungsgeten/org-brain#177]
I have a problem when I try to make a "brain-friends" link to an entry from another org file.

![Brain](https://user-images.githubusercontent.com/29939805/61182162-dcd2ff80-a62f-11e9-99e2-aa6a5fbd725f.png)

Any idea ?

**Comment by ThanosPal** [comment]
Same here. It happens with all links that make a relation between nodes. Anyone knows what's up?

**Comment by Kungsgeten** [comment]
Hmm, seems to work for me. Are you sure that the file you're in is in your `org-brain-path`? You could also try running `M-x org-brain-update-id-locations` first.

**Comment by bepolymathe** [comment]
Yes `M-x org-brain-update-id-locations` seems to solve the problem...
