### ISSUE TITLE
Insert timestamp when create new headline

### ISSUE THREAD

**Issue by bepolymathe** [Kungsgeten/org-brain#178]
Hi,

Is there is a way to insert a timestamp (or other proprieties) in the block PROPRIETIES when i create new headline ("h" key) ?
Thanks ;-)

**Comment by Kungsgeten** [comment]
Yes you could add a function to `org-brain-new-entry-hook`. I'm not sure which function you should add though.

**Comment by bepolymathe** [comment]
Thks. Do you have an example I could use as an inspiration?

**Comment by Kungsgeten** [comment]
Well the challenge is to find/write a function which does what you want :) After some Googling I found this: https://stackoverflow.com/questions/12262220/add-created-date-property-to-todos-in-org-mode

I then think you could add this (if you have `org-contrib` available) to your init-file:

```
(require 'org-expiry)
(add-hook 'org-brain-new-entry-hook 'org-expiry-insert-created)

```

**Comment by bepolymathe** [comment]
Great ! I confirm it works !

![image](https://user-images.githubusercontent.com/29939805/61776044-7782c980-adfa-11e9-8095-49e9ffd2688a.png)
