### ISSUE TITLE
Picture layout problems because of indent-tab-mode

### ISSUE THREAD

**Issue by hugovalk** [Kungsgeten/org-brain#184]
Layout of the visualization is broken when `indent-tabs-mode` is set to `t`. 
On my Ubuntu 19.04 / Emacs 26.1 this happened to be the case. 
On my Arch Linux (virtualbox) environment this was NOT the case. 
I reuse the same init.el on both environments and had not set the variable. 

Either the documentation should mention that you need to put in init.el: 

    (setq-default indent-tabs-mode nil)

Or, the code should detect the tabs mode and correct for it. Part of where this goes wrong, for example, is line 1680:

    (let ((half-title-length (/ (string-width title) 2)))
      (if (>= half-title-length (current-column))
          (delete-char (- (current-column)))
        (ignore-errors (delete-char (- half-title-length)))))

The line contains tabs and removing this amount of characters moves you back to the previous line. Resulting in a visualization like:

![ubuntu](https://user-images.githubusercontent.com/1302261/61746181-70789e80-ad9b-11e9-9bb9-ed93a239e7cd.png)

Instead of:

![ubuntu2](https://user-images.githubusercontent.com/1302261/61746291-9f8f1000-ad9b-11e9-9d0d-c60c09c2d4dc.png)

**Comment by Kungsgeten** [comment]
Thank you! I've gotten some comments earlier about the text not rendering like it should. Maybe those issues are related with this one. I'll try to look into it!

**Comment by Kungsgeten** [comment]
`indent-tabs-mode` should now be `nil` for the `org-brain-visualize` buffer. Could you please try and see if this solves the issue?

**Comment by hugovalk** [comment]
Hi,
org-brain depends on org 9.2 now, if I'm not mistaken. The built-in version in Emacs from the Ubuntu 19.04 repository is still on 9.1. Also, I see now this error with use-package in my init.el:

    Error (use-package): Failed to install org-brain: Assertion failed: (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))

**Comment by Kungsgeten** [comment]
Yes, it does (even though the dependency is mostly because they've deprecated an old function in 9.2). You should be able to upgrade to the newest `org-mode` version through the Emacs package manager though.

That error seems strange. Try to run `M-x package-list-packages` and try again.

**Comment by hugovalk** [comment]
Hi, sorry it took a while (I'm on holiday). I have indeed upgraded everything to latest. Your fix for the display issues works in version `20190809.1013`

**Comment by Kungsgeten** [comment]
Great! I'm closing this then :)
