### ISSUE TITLE
feature: optionally strip drawers and #+ declarations from entry when visualizing

### ISSUE THREAD

**Issue by herrsimon** [Kungsgeten/org-brain#188]
It would be very useful if org-brain had the option to skip drawers and #+ declarations when visualizing entries through org-brain-visualize

**Comment by Kungsgeten** [comment]
Maybe there could be an option to have a "filter function" which takes the entry text as input and returns a new string.

**Comment by herrsimon** [comment]
I had another thought on this. Instead of a filter function, how about an optional split-view for org-brain-visualize, where the content of the currently active node is shown in a separate window? This window would then auto update itself as soon as another node is selected and could even have its own 'org-brain-show-mode' for hooks, keybindings etc.

**Comment by Kungsgeten** [comment]
Wouldn't it make more sense to have a "follow mode" or similar (I think `dired` has it for pictures), where the split-view consists of `org-brain-visualize` and the actual org-file and its content (focusing on the headline visualized)?

**Comment by herrsimon** [comment]
That's more or less what I meant. Actually, I just rediscovered that orgmode also has this for the agenda view (org-agenda-follow-mode, by default bound to 'F' in an agenda view), and if org-brain had the same functionality, this would be awesome. Looking at the orgmode code, it seems that the functionality has to be slightly extended to also show files instead of headlines. Unfortunately my lisp skills are extremely limited but I could at least help with properly documenting the feature afterwards.

**Comment by Kungsgeten** [comment]
Now its possible to use "follow mode" for `org-brain-visualize`. Toggling it is bound to `V` when visualizing. There's also a hook name `org-brain-visualize-follow-hook`, I like the following:

```
(add-hook 'org-brain-visualize-follow-hook
          (lambda ()
            (unless (org-brain-filep (org-brain-entry-at-pt))
              (org-narrow-to-subtree))))
```
