### ISSUE TITLE
Not quite an issue: regenerating org-id-file-locations

### ISSUE THREAD

**Issue by Trevoke** [Kungsgeten/org-brain#195]
Hello! I really like this tool. Thank you for creating and maintaining it.

I have the interesting situation where I'm using this across a number of machines as well as a number of platforms, and as such I have to regenerate the org-id-location file for org-brain so that it works well. Here's the snippet of code I use to do this:

```elisp
(org-id-update-id-locations
 (mapcar (lambda (file) (string-join `(,org-brain-path "/" ,file)))
         (directory-files org-brain-path)))
```

Obviously the separator isn't always the right separator, but I'm OK with this for right now. Maybe it'll be useful to someone else :)

**Comment by Kungsgeten** [comment]
Hi! I'm glad that you like the package!

Is there a difference between this function and `org-brain-update-id-locations` which is provided by `org-brain`? You can run it with `M-x`. The implementation looks like this:

```
(defun org-brain-update-id-locations ()
  "Scan `org-brain-files' using `org-id-update-id-locations'."
  (interactive)
  (org-id-update-id-locations (org-brain-files)))
```

**Comment by Trevoke** [comment]
Ah, the built-in implementation looks superior :) I did not find it when I was looking for it. Thanks :)
