### ISSUE TITLE
Error (use-package): Failed to install org-brain

### ISSUE THREAD

**Issue by anthrolisp** [Kungsgeten/org-brain#196]
Using the use-package setup in the README file I get the following error:

```
Error (use-package): Failed to install org-brain: https://melpa.org/packages/org-brain-20190521.756.el: Not found
Error (use-package): Cannot load org-brain
```

**Comment by Kungsgeten** [comment]
Try to run `M-x package-list-packages` and wait for it to update. Then try again. That usually works for me when I get error messages like that.

**Comment by anthrolisp** [comment]
Worked. Thank you!
