### ISSUE TITLE
Completion Consistency

### ISSUE THREAD

**Issue by alanz** [Kungsgeten/org-brain#197]
When invoking `org-brain-refile`, the possible target completions are listed in the form
"Heading Name (Filename.org)" and so you can narrow it down by typing the start of the heading, then see what file it is in.

When adding a child, friend, etc the target completions are listed as
"Filename::Heading Name"

This means you need to first know what file a heading is in, before narrowing things down. With the default emacs completion, that is.

I presume the `::` variant allows more control of an exact path, but the completion story is not so good.

**Comment by Kungsgeten** [comment]
Hi! `org-brain-refile` uses `org-refile` in its implementation, and it is `org-refile` which determines how the targets are listed.

I have however now added a variable named `org-brain-headline-entry-name-format-string` which you can modify if you want to change how the name of headline entries are shown in `org-brain`. You can check the documentation for the `format` function in Emacs for information on how format strings work.

As an example, if you'd like to have the "Heading Name (Filename.org)" format, you can set `org-brain-headline-entry-name-format-string` to `"%2$s (%1$s.org)"`.
