### ISSUE TITLE
(mapcan #'org-brain--file-targets) causes raspberry pi to eventually reboot

### ISSUE THREAD

**Issue by Trevoke** [Kungsgeten/org-brain#199]
I've tried to set up a GTD / brain station at home on a raspberry pi. It's obviously slower than a normal computer, and also has less memory ( ~ 1GB). I've found that I have too much data in my org-brain (I've tried by adding the files one at a time into the directory and running `org-brain-visualize`) and after a certain number of entries is reached, the function that generates the names of the entries "does not return", memory usage for emacs steadily increases, and eventually forces the Pi to reboot.

I believe that if the names were generated / pre-cached, this problem would go away. I can't think of another solution off the top of my head, and I think this solution has some issues, but right now the only other solution I can think of involves changing the backend to sqlite or something similar.

**Comment by Kungsgeten** [comment]
Not really sure what to do about this. I think it should just load one file into memory at a time when doing this, but I might be wrong. It could maybe be the case that the garbage collection isn't run while the `mapcan` is running, but I'm not sure.

**Comment by Kungsgeten** [comment]
The implementation of `org-brain--file-targets` has changed quite a bit now. However it now works by opening all org-brain files as buffers, so my guess is that it doesn't solve this issue. The optimization done is geared towards speed rather than memory, do I probably won't fix this.

**Comment by Trevoke** [comment]
As a matter of fact,  just tried to both update the id locations and then
to do `org-brain-visualize` and, while `org-brain-visualize` was a bit
slow, it worked quite well!

**Comment by Kungsgeten** [comment]
That's great, closing this then :)
