### ISSUE TITLE
Rename Org-Brain File

### ISSUE THREAD

**Issue by braegel** [Kungsgeten/org-brain#2]
it would be great to have a function for renaming an org-brain file which renames the file and changes all Brainchildrens accordingly.

**Comment by Kungsgeten** [comment]
I've added `org-brain-rename-entry` which should do that.

**Comment by braegel** [comment]
Thank you for the work. I spent the last night converting my digitial live to org-brain. I love it.

However the new command `org-brain-rename-entry` is not available after `M-x` neither from visual mode by pressing `r`.

**Comment by Kungsgeten** [comment]
Whoops! Should be fixed now :)

**Comment by braegel** [comment]
Thank. But now i have a new Issue.

After I enter the `newentry` i always get this new error: `Symbol's function definition is void: string-join`

**Comment by Kungsgeten** [comment]
Ok, seems `string-join` is part of `subr-x`, and that isn't required by default. I've commited a fix (hopefully) so please try again. Thank you for reporting these issues.

**Comment by braegel** [comment]
Hi there - currently `org-brain-rename-entry` seems to be gone. Is there currently a way to rename an org-brain file? Thanks for your good work! I use org-brain in my daily routine!

**Comment by Kungsgeten** [comment]
Hi! Yes I removed a lot of functions in version 0.4, and some of them changed name. You can use `M-x org-brain-set-title` to change the name/title of an entry (defaults to entry at point, if any). You can press `t` in `org-brain-visualize` to rename the current entry.

**Comment by braegel** [comment]
Thanks! That works for me!
