### ISSUE TITLE
Bugs visualizing parents and siblings

### ISSUE THREAD

**Issue by chemmi** [Kungsgeten/org-brain#200]
Hi,

I ran into two bugs visualizing parents and siblings.

The first one:
With some entries, my output looked like this:

```
         +-Sib1
         +-Sib2
         +-Sib3
   index-+-Sib4
     |   +-test1
     |   +-test2
     |
     V
MyPrettyEntry
```
(I assume that `index` should be on the height of `test2`, right?)

The second bug:
Actually such a shift is not bad in the first place but it raised an error when I switched off the visualization of the history. This was due to some static values used in the function `org-brain--vis-parents-siblings` which assume that we have a certain amount of lines already written.

I fixed both these bugs in a pull request. Details in the commit messages.

Regards,
Christian

**Comment by Kungsgeten** [comment]
Hi! No, the first issue you list is not a bug. It is by intent (I think it looks better). The second issue seems like a bug though. The history visualization is pretty new, implemented by @drbronner. I'll have a look at your PR. Thanks!

**Comment by chemmi** [comment]
Thanks for your quick reply! And you're right: Looks better :)
