### ISSUE TITLE
org-brain-goto deletes file content

### ISSUE THREAD

**Issue by tmdemelo** [Kungsgeten/org-brain#202]
Calling `org-brain-goto` to open entries corresponding to non-visited files deletes the whole file content.

It affects other functions, such as visiting files from the org-brain-visualize interface and inserting relationships.

I've tracked it down and it started happening since commit 28d05bcbdaf30a3af29246601a2996f8bcde5f28.

Sample reproduction:
- Create a file `foo.org` in the org-brain folder, write some text in it and save the file.
- Make sure the buffer visiting `foo.org` is killed.
- eval `(org-brain-goto "foo")`

**Comment by Kungsgeten** [comment]
Wow, I can't believe I missed this! Sorry if it caused you any trouble! It should be fixed now.

**Comment by tmdemelo** [comment]
No worries, I'm glad I could help catching it.

Thanks for the prompt fix and the great software.
