### ISSUE TITLE
Collect links from :childless: entries as resources of their parent entry

### ISSUE THREAD

**Issue by Wetlize** [Kungsgeten/org-brain#204]
Hi! Right now `org-brain-visualize` displays entries that being `childless` as part of their parent's content. This is useful and desirable, however, links from such entries are not being collected as resources. It would be very useful if it would collect and include them as resources of their parent entry.

Here is a quick example of a file entry that represents what am I talking about:
```
#+FILETAGS: childless

File content.

- [[https:foo.com][foo link]]
- [[https:bar.com][bar link]]

Still file content.


* Childless headline

  Content of the childless headline.

  [[https:foobar.com][foobar link]] that need to be included as a resource of the parent (i.e. file level) entry.

** Same thing should apply for any other children in the hierarchy.

* [[https:baaz.com][baaz link]] this should be a resource too.

  Some other content.

** Same thing should apply for any other children in the hierarchy.
```

Basically, while `foo link` and `bar link` are being displayed as resources of this file entry, the `foobar link` and `baaz link` still being skipped, even though they are part of `childless` content.

How difficult it would be for org-brain to implement such thing? I assume it would also require to handle cases with multiple tags, e.g. `childless` in combination with `resourceless` should not cause collection of resources. I know elisp, but I'm quite unfamiliar with org-mode and org-brain codebases to reason about this.

**Comment by Wetlize** [comment]
After shortly investigating how `org-brain-resources` being resolved, I found that removing optional `ALL-DATA` flag in [org-brain-entry-data](https://github.com/Kungsgeten/org-brain/blob/master/org-brain.el#L591) solves my issue. 

Is there any reason why this flag need to be forcefully set to `t`? If this just a preference, can it be set instead as a user option (e.g. as something akin to `org-brain-collect-resources` predicate variable)?

**Comment by Kungsgeten** [comment]
Hi! This seems like a "bug". I agree that resources from children should be picked up if the parent has `:childless:`. I'll look into it :)

**Comment by Kungsgeten** [comment]
This should be fixed now! Thanks for reporting it :)

**Comment by Wetlize** [comment]
Thanks for the quick reply and taking your time fixing this!
