### ISSUE TITLE
org-brain-visualize does not find necessary files

### ISSUE THREAD

**Issue by tristanstoeber** [Kungsgeten/org-brain#205]
Hei Erik,
your org-brain mode seems fantastic and I would really like to get it to work.

I installed it via melpa and copied the recommended snippet of code into my .emacs file and 
I modified the following line to point to my org brain path (setq org-brain-path "~/org").

For test purposes I do create the file index.org with two headlines.
Each headline gets an index via Mx org-id-get-create.

But when I try to evaluate M-x org-brain-visualize, I get the following error instead of an overview of my connections.
Opening directory: No such file or directory, ~/org/brain/data/cc/958736-3697-41fa-bd8f-b8cbdcffddbc

What to do?
Best,
Tristan

**Comment by tristanstoeber** [comment]
Ok I think I have now understood it. Ids in files and headlines must be created via the org-brain-visualize function. I created headline ids directly. I can live with that.

**Comment by Kungsgeten** [comment]
Hi! It should work to add IDs manually. What you might have to do if you run into problems like this is to execute `M-x org-brain-update-id-locations`.
