### ISSUE TITLE
org-attach-file-list sometimes can't find directory of attachments

### ISSUE THREAD

**Issue by Wagk** [Kungsgeten/org-brain#208]
When attempting to access headlines of files (e.g `foo/boo::bar`), I'm getting errors of this nature:

```
org-attach-file-list: Opening directory: No such file or directory, c:/Users/<Name>/Sync/wiki/computing/data/01/812420-9307-4228-8c6d-d04df9ed2650
```

This occurs even after calling `org-brain-update-id-locations`. This does not occur when I'm attempting to go to a file (e.g `foo/boo` works).

I am currently running org 9.2.5

Am I doing something incorrectly?

**Comment by Wagk** [comment]
I am currently running Org-mode 9.2.5, if that helps.

**Comment by Kungsgeten** [comment]
I think this is the same problem as #203 solved. Its a change made to org-attach, but now (or soon) it seems like it should be updated. Read the discussion in the linked PR. The PR also includes a solution, which you could try.

**Comment by Kungsgeten** [comment]
I'm closing this since the `org-mode` related updates has been made in org-mode master.
