### ISSUE TITLE
org-brain-visualize does not work

### ISSUE THREAD

**Issue by jcguu95** [Kungsgeten/org-brain#220]
I customized as in `readme.md` and assigned the path to `$MYORGDIR/brain`. While executing `org-brain-visualize`, I was prompted to enter one entry name. After that, I got an error
`org-brain--hist-entries-to-draw: Wrong type argument: stringp, nil`.

**Comment by Kungsgeten** [comment]
I'm sorry to hear that. Could you use `M-x toggle-debug-on-error`, try again, and report what it says?

**Comment by jcguu95** [comment]
Wow and it works! What's the magic behind it?
