### ISSUE TITLE
org-brain-add-child to a sub directory 

### ISSUE THREAD

**Issue by j1e8WTb1A1nReiUc** [Kungsgeten/org-brain#222]
When you execute org-brain-add-child and provide a name,
a new file is created in the root directory of the specific brain session.

I was expecting a file path to be valid input. Otherwise, what is the purpose of subdirectories inside org-brain-path to be scanned recursively for files?

My goal is to use subdirectories as a further organisation tool.

**Comment by Kungsgeten** [comment]
If you write something like `text-editors/emacs` then the result should be that a file named `emacs.org` is created in the `text-editors` directory (created if it doesn't exist already) inside your brain folder. The `emacs` entry is then added as a child to the entry from which you ran `org-brain-add-child`.

**Comment by j1e8WTb1A1nReiUc** [comment]
Thanks!
