### ISSUE TITLE
Completion for existing tags 

### ISSUE THREAD

**Issue by Aquan1412** [Kungsgeten/org-brain#228]
Is there a way to get completion for existing tags in org-brain? Right now I have to enter tags from memory, since apparently the various org-brain files don't now which tags exist in other org-brain files. Obviously, this leads to lots of similar tags with small errors or similar meaning (HOWTO, How-to, Tutorial, tutorials...), rendering the idea of tagging basically useless for me.

**Comment by Kungsgeten** [comment]
There's no built-in way to do this. One way could be to have a separate org-file where you define all tags, and to then use it as a setup-file in all other files. Yet another way might be to set the variable `org-tag-alist` to the tags you want to include, maybe as an advice around the `org-brain-set-tags` function.

More info [here ](https://orgmode.org/manual/Setting-Tags.html#Setting-Tags)and [here](https://orgmode.org/manual/In_002dbuffer-settings.html).

**Comment by Aquan1412** [comment]
Thank you for the quick answer. I'll see if I can set something up that works for me.

**Comment by Aquan1412** [comment]
I managed to hack a little snippet together to find all the tags in the org-brain files and add them to the org-tag-alist. They are then saved in a file in the org-brain-path to avoid scanning the files every time. It's pretty ugly, but for me it seems to work, maybe someone else can also use it. I'd be happy for suggestions and corrections.

```elisp
(defun print-to-file (filename data)
  (with-temp-file filename
    (prin1 data (current-buffer))))

(defun read-from-file (filename)
  (with-temp-buffer
    (insert-file-contents filename)
    (cl-assert (eq (point) (point-min)))
    (read (current-buffer))))

(setq org-brain-tag-storage (expand-file-name (concat org-brain-path "/" ".org-brain-tags")))

(defun org-brain-find-all-tags ()
  (interactive)
  (let ((brain-files (directory-files org-brain-path))
	(tag-alist ()))
    (dolist (tmp brain-files)
      (if (string-suffix-p ".org" tmp)
	  (with-temp-buffer "*org-brain-scan-tags*"
			    (insert-file-contents (expand-file-name (concat org-brain-path "/" tmp)))
			    (let ((current-tags (org-get-buffer-tags)))
			      (unless (eq current-tags nil)
				(setq tag-alist (append tag-alist current-tags))))
			    )
	)
      )
    (setq tag-alist (delete-dups tag-alist))
    (print-to-file org-brain-tag-storage tag-alist))
  )

(defun org-brain-get-stored-tags ()
  (interactive)
  (setq org-tag-alist (read-from-file org-brain-tag-storage)))

(add-hook 'org-brain-visualize-mode-hook 'org-brain-get-stored-tags)
```
