### ISSUE TITLE
Error running timer ‘org-indent-initialize-agent’: (void-function org-time-add)

### ISSUE THREAD

**Issue by mjakefranklin** [Kungsgeten/org-brain#232]
I've attempted to install org-brain via use-package, using the following config taken from README (with the evil-specific stuff commented out):

```
(use-package org-brain :ensure t
  :init
  (setq org-brain-path "~/org/brain")
;; For Evil users
;;(with-eval-after-load 'evil
;;  (evil-set-initial-state 'org-brain-visualize-mode 'emacs))
  :config
  (setq org-id-track-globally t)
  (setq org-id-locations-file "~/.emacs.d/.org-id-locations")
  (push '("b" "Brain" plain (function org-brain-goto-end)
          "* %i%?" :empty-lines 1)
        org-capture-templates)
  (setq org-brain-visualize-default-choices 'all)
  (setq org-brain-title-max-length 12)
  (setq org-brain-include-file-entries nil
        org-brain-file-entries-use-title nil))
```

After installing, I'm getting the following message over and over again:

```
Error running timer ‘org-indent-initialize-agent’: (void-function org-time-add)
```

I deleted the above config entry, deleted ~/.emacs.d/elpa, and recompiled.  From there, I just did a ```package-install``` of org-brain, but I get the same result.  Am I missing a step somewhere?  Current Emacs version is 26.3

Thanks!

**Comment by Kungsgeten** [comment]
Hmm, that is strange. I don't think `org-brain` is using `org-time-add` anywhere. If you try `M-x org-version` what do you get?

**Comment by mjakefranklin** [comment]
```Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)```

Strange indeed, I have less experience working with Emacs on a Mac

**Comment by mjakefranklin** [comment]
This was somehow my mistake with the ordering of init.el, my apologies, it's working now (both on MacOS and Debian)
