### ISSUE TITLE
See tags in org-brain visualize ?

### ISSUE THREAD

**Issue by bepolymathe** [Kungsgeten/org-brain#234]
Hi,

Is there a way to make the tags appear in "Org-brain visualize" (space+"o "+"v") ?

**Comment by Kungsgeten** [comment]
Hi! Yes, have a look at "Customizing the look of entry titles" in the README.

**Comment by bepolymathe** [comment]
Ok, thanks for reply. I hadn't read that well ;-)

I try this but it don't works. :thinking: 

```
  (defun org-brain-vis-title-append-functions ()
    (interactive)
    (let ((org-brain-entry-tags-string)))
      )

```

**Comment by Kungsgeten** [comment]
`org-brain-vis-title-append-functions` isn't a function itself, but a variable which holds a list of functions. I think this should work:

`(setq org-brain-vis-title-append-functions '(org-brain-entry-tags-string))`

**Comment by bepolymathe** [comment]
Yeah, it made sense. Thanks for the clarification. 

By the way, another suggestion. It would be very useful to be able to display the date as well. I sometimes have many entries that refer to the same person/configuration ("Meeting with Oliver", "Meeting with Olivier", etc). Thanks to the code below, I insert a creation date in each entry
```

 (require 'org-expiry)
 (add-hook 'org-brain-new-entry-hook 'org-expiry-insert-created)
 (add-hook 'org-brain-refile 'org-id-get-create)
 (add-hook 'org-brain-refile 'org-expiry-insert-created)

```
Wouldn't it be possible to display it in the search with org-brain visualize? Maybe with something like that:

`(setq org-brain-vis-title-append-functions '(org-brain-entry-created-string))`

**Comment by Kungsgeten** [comment]
Yes, its possible as long as you know how to get the data that you want from the entry. I haven't tried it, but I think this function should work:

```
(defun org-brain-get-created (entry)
  (org-entry-get (org-brain-entry-marker entry) "CREATED"))
```

Now you could add that to `org-brain-vis-title-append-functions`.

**Comment by bepolymathe** [comment]
That's just great, it works. Thank you for your advice, which also helps us understand the logic behind it. 

So I have an interesting system with the date at the beginning + name of the entry + tags. That's what it looks like (for documentation here). 

```
(setq org-brain-vis-title-append-functions '(org-brain-entry-tags-string))
(defun org-brain-get-created (entry)
  (org-entry-get (org-brain-entry-marker entry) "CREATED"))
(setq org-brain-vis-title-prepend-functions '(org-brain-get-created))
```

Thank you for your help. Happy end of year parties.
