### ISSUE TITLE
Delete more than one entry

### ISSUE THREAD

**Issue by bepolymathe** [Kungsgeten/org-brain#236]
Hi,

The `org-brain-entry-separator` command allows you to create multiple entries at once by separating them with ` ; ` character. 

Is it possible to do the same thing to delete entries. It doesn't seem to work by default?
Thanks ;-)

**Comment by Kungsgeten** [comment]
Hi! No, it isn't possible to delete more than one entry at a time using `org-brain-delete-entry`. It is possible though to delete several entries at a time via `org-brain-visualize`. While visualizing you can press `s` to select an entry (the one the point/cursor is over). After you've selected the entries you can press `S d` to delete the selected entries.

See the end of the _org-brain-visualize_ headline in the README for more info on selection.

**Comment by bepolymathe** [comment]
Ok, thanks for reply. This is already an interesting solution. I'm still discovering features ;-) Thanks for your work.
