### ISSUE TITLE
Feature: Format text entry like org does (regarding tables and substructure)

### ISSUE THREAD

**Issue by hokreb** [Kungsgeten/org-brain#240]
Thanks a lot for this great tool, it really helps me to organize my knowledge!

There is one thing, I would find great if possible (or maybe it is, but I am not aware):
Actual I would like to format text entry with the typical outlining possiblities of org-mode. If I create a table with a width bigger than the actual buffer, each line gets wrapped, so that the table is not readable anymore. 
Additionally I would like to use sub outlines in the text info of a head entry. Maybe it could be done, that the subheadlines will be shown, if the subheadlines has no org-brain-id. Than it would be possible to structure the information shown in the text entry.

**Comment by Kungsgeten** [comment]
Hi! Glad you like the package. I don't quite understand what you mean regarding the text format of the entries. `org-brain` gets the text properties from the text it fetches in the file's `org` buffer when scanning, so I think it should look the same. Is it only the case that lines get wrapped? My `org` tables get wrapped in `org-mode` too, but that could be because of some package I'm using.

You can show subheadings by using the `showchildren` or `childless` tag on the entry. At the moment it isn't possible to show subheadings without an ID, while hiding those that have an ID. I'll have a look into that though!

**Comment by hokreb** [comment]
The tag showchildren did the trick. Thats really great! 

The org-brain version I have from melpa does show subchildren without an ID. No need to verify.

Regarding the line wrap, I didn't think of special modes which might cause the line wrapping. But of course this could be the case. I will investigate this more.

Thanks a lot, also for the very fast replay, As the main pain point from my side is not valid anymore I close this ticket.

Once again, thanks a lot for this really useful package.

**Comment by Kungsgeten** [comment]
Hi! Glad you enjoy the package!

I don't quite understand your issue regarding the look of the entry text. I think that `org-brain` should insert it the way `org-mode` makes it look. Maybe if you provide a screenshot I can see what you mean.

You can use the tag `showchildren` or `childless` on an entry to show subheadings. It might be a good idea though that subheadings without an ID show up in the entry text. Here's an experimental version you could try:

```
(defun org-brain--non-entries-in-buffer-text (level)
  "Text of subtrees at LEVEL in `current-buffer' which aren't part of `org-brain'."
  (let ((inhibit-message t))
    (apply #'concat
           (org-ql-select (current-buffer)
             `(and (level ,level)
                   (not (property "ID")))
             :action
             '(progn
                (org-mark-subtree)
                (buffer-substring-no-properties (region-beginning) (region-end)))))))

(defun org-brain-text (entry &optional all-data)
  "Get the text of ENTRY as string.
Only get the body text, unless ALL-DATA is t."
  (when-let*
      ((current-level 0)
       (entry-text
        (if (org-brain-filep entry)
            ;; File entry
            (with-temp-buffer
              (ignore-errors (insert-file-contents (org-brain-entry-path entry)))
              (goto-char (org-brain-first-headline-position))
              (let ((start (if all-data
                               (point-min)
                             (or (save-excursion
                                   (when (re-search-backward org-brain-keyword-regex nil t)
                                     (end-of-line)
                                     (point)))
                                 (point-min)))))
                (if (let ((filetags (org-brain-get-tags entry)))
                      (or (member org-brain-show-children-tag filetags)
                          (member org-brain-exclude-children-tag filetags)))
                    (buffer-substring-no-properties start (point-max))
                  (rename-buffer "*ob-showchildren-scan*")
                  (delay-mode-hooks (org-mode))
                  (concat (buffer-substring-no-properties
                           start (org-brain-first-headline-position))
                          (org-brain--non-entries-in-buffer-text 1)))))
          ;; Headline entry
          (org-with-point-at (org-brain-entry-marker entry)
            (setq current-level (org-current-level))
            (let ((tags (org-get-tags nil t)))
              (unless (and (member org-brain-exclude-text-tag tags)
                           (not all-data))
                (unless all-data
                  (goto-char (cdr (org-get-property-block)))
                  (end-of-line))
                (if (or (member org-brain-exclude-children-tag tags)
                        (member org-brain-show-children-tag tags))
                    (buffer-substring-no-properties (point)
                                                    (progn
                                                      (org-end-of-subtree t)
                                                      (point)))
                  (concat
                   (buffer-substring-no-properties (point)
                                                   (save-excursion
                                                     (or (org-goto-first-child)
                                                         (org-end-of-subtree t))
                                                     (point)))
                   (org-brain--non-entries-in-buffer-text (1+ current-level))))))))))
    (if all-data
        (org-remove-indentation entry-text)
      (with-temp-buffer
        (insert (org-remove-indentation entry-text))
        (goto-char (org-brain-first-headline-position))
        (if (re-search-backward org-brain-resources-start-re nil t)
            (progn
              (end-of-line)
              (re-search-forward org-drawer-regexp nil t))
          (goto-char (point-min)))
        (buffer-substring (point) (point-max))))))
```

If you add that to your config, after `org-brain` has loaded, I think you'll get what you want. The downside is that its slower than the current version of the function.

**Comment by Kungsgeten** [comment]
Yes, `showchildren` will show all subheadings. However if you want to show only the subheadings without an ID, but not those who have an ID, you'd have to use the new code  above.
