### ISSUE TITLE
Back link: List org mode file as resource when it links to a brain: type link

### ISSUE THREAD

**Issue by riclage** [Kungsgeten/org-brain#241]
When I edit an org-brain file, adding a link to another file lists it as a resource in the visualize mode. That is great!

Is there a way to do the same when an org-mode file links to the org-brain file using the `brain:` link type? That would create a back link from the org-brain file to the org-mode one where the link was originally created.

For example: Say I have an org-brain concept called "Lisp" and an org-mode file called "lisp-book.org". In the lisp book file, I may want to reference Lisp with a [[brain:lisp]] link. By doing so, it would be great to have a section in the Lisp org-brain concept linking back to the "lisp-book.org" file automatically.

Would that be possible? Hope my explanation is clear. Happy to give you more details as needed.

Thanks!

**Comment by Kungsgeten** [comment]
Have a look at the variable org-brain-ignored-resource-links. I think you'll get the behaviour you want if you remove the "brain" element from it.

**Comment by riclage** [comment]
Thanks but nothing seems to happen when I remove it.

Adding a brain link either to the org-mode file back to my org-brain file OR adding a brain link from an org-brain file to another does not make it show up in the resources list.

**Comment by Kungsgeten** [comment]
Hmm, that's strange. The following works for me:

```
(setq org-brain-ignored-resource-links
      '("fuzzy" "radio" "brain-child" "brain-parent" "brain-friend"))
```

Now `brain` links show up as a resource.

**Comment by riclage** [comment]
I was changing the `elpa/org-brain.el` file when I should have put the change you proposed on my `.emacs`. Thanks, now it kinda works.

Suppose I have a `dog.org` brain file and an org file called `wild-dogs.org` where I'm adding notes about wild dogs in general. In this file, I want to add a link to the [[brain:dog-id]] file. Then, in "visualize" mode, when I see the "dog" concept, I want to see the `wild-dogs.org` file listed as resource.

What you suggested works if inside `dog.org` I link to another brain file, say [[brain:cat-id]]. Then in the dog concept, the cat one is listed as a resource.

Hope it's clear. Thanks again the quick answers. Appreciate it.

**Comment by riclage** [comment]
I think what I mean to do is modify the [`org-brain-link-complete`](https://github.com/Kungsgeten/org-brain/blob/master/org-brain.el#L2794) function for the "brain" link type and call the [`org-brain-add-resource` ](https://github.com/Kungsgeten/org-brain/blob/master/org-brain.el#L2193) where the `link` parameter is the `entry` inside org-brain-link-complete and `entry` is the `choice`.

Does that make sense?

**Comment by Kungsgeten** [comment]
Yes I think I understand. You'd like to have a two-way link? So when you create a link from A -> B there's also a resource in B -> A? I guess there could be another type of link, like `brain-backlink`, which could be created in the B entry.

I think the whole concept is very similar to friend entries though? Couldn't you use the `brain-friend` link, or is there are reason that you don't want to add the entries as friends?

**Comment by riclage** [comment]
> brain-backlink
Or `brain-resource`?

The way I'm using org-brain, is by keeping "concepts" and "resources" about them separate. When I read articles or books, they talk about the concepts I want to keep track of, but I don't see them as brain "concepts" themselves.

This is a semantical separation and also practical one: It keeps the concepts I keep track of cleaner and more concise, making it easier to navigate through them.

**Comment by Kungsgeten** [comment]
I've added a variable named `org-brain-backlink` which you can set either to `t` or to a string. This will create backlinks (either a `brain` link or a `file` link, depending on context of where  the link was created). If set to a string it will add a prefix to the backlink description.

**Comment by riclage** [comment]
This is awesome, thank you so much!

One thing I noticed so far when inserting the back link to a file is that the link is to the full file path. Is there a way to make the path relative or in terms of the `~` root?

**Comment by Kungsgeten** [comment]
Good idea! Now the file link is relative to the file where it was inserted.

**Comment by riclage** [comment]
This is awesome and it's working really well so far. Thanks again!

**Comment by michaelsjackson** [comment]
> org-ql is an incompatible package.
> 
>      Status: Incompatible because it depends on Emacs 26.1.
>      Archive: melpa
I am still using emacs 25.3  because of various reasons (troubles I got after updating to later versions).
