### ISSUE TITLE
`org-ql` makes `org-brain-goto` slow

### ISSUE THREAD

**Issue by HopeForToday** [Kungsgeten/org-brain#246]
With the newest version of `org-brain`,  the `org-ql` war introduced. Each time I ran `org-brain-goto` command, `org-ql` open all my brain files (140 file entries, toal 414 entires), which make Emacs slow... 

Anything help or optimization?

**Comment by Kungsgeten** [comment]
Hi! Yes, it is a bit slow on my computer too. The slow part is having to open all of the files. If you have stuff in `org-mode-hook` and `find-file-hook` it takes some time to open the files. It should be MUCH faster when you've run the command once, and all of the files are open. Is it still slow the second time you run it?

**Comment by Kungsgeten** [comment]
There's a bit of discussion at https://github.com/alphapapa/org-ql/issues/88 if you're interested.

**Comment by HopeForToday** [comment]
Thanks for your response.

I test it again. It spend about 1 second to open `org-brain-goto` (second time), 0.5 second with the old version in my computer. It's slower.

**Comment by namdnguyen** [comment]
Wow, I read the discussion in the org-ql issue you linked. This is a difficult problem. I really appreciate the work you're putting in upstream to help improve performance for org-brain.

**Comment by Kungsgeten** [comment]
I've removed the `org-ql` dependency in the latest commit. Instead a simple cache has been implemented, so `org-brain` should be faster than before.

**Comment by namdnguyen** [comment]
Oh, cool. I'll give it a try and report back my experience.
