### ISSUE TITLE
org-brain-visualize opens all files

### ISSUE THREAD

**Issue by tristanstoeber** [Kungsgeten/org-brain#251]
hey,

first of all thanks for this fantastic package. i started using org-brain intensively and love it!

just reinstalled org-brain and realized that when i call org-brain-visualize it seems to open all org-brain-files in the background. when opening the buffer list C-x C-b, all files are visualized.

best,
tristan

**Comment by BobCromwell** [comment]
me too，sometimes it hit “too many files opened” error

**Comment by Kungsgeten** [comment]
Yes, since I introduced `org-ql` for scanning files all files needs to be opened. Some people has experienced issues because of `org-ql`, so I'm thinking about maybe removing it.

**Comment by BobCromwell** [comment]
> Yes, since I introduced org-ql for scanning files all files needs to be opened. Some people has > > experienced issues because of org-ql, so I'm thinking about maybe removing it.

I think  org mode should fix this...  If org-agenda will hit "too many files opend" error too.

**Comment by Kungsgeten** [comment]
I've removed the `org-ql` dependency with the latest commit. That should fix this issue.

**Comment by tristanstoeber** [comment]
thanks! warmly appreciated

**Comment by adam52** [comment]
Hmm... this did not work for me. I have the latest `org-brain` installed (I do not have `org-ql` installed) and everytime I boot Emacs, `org-mode` insists on opening all of my `org-brain` files.

I have a little over 800 of these and each is full of of `LaTeX` code. So easily 5min is spent at launch, waiting for Emacs to render LaTeX previews.

If we could somehow lazy load these files, that would be fantastic!

**Comment by Kungsgeten** [comment]
@adam52 Are you using the latest version of `org-brain`? It shouldn't open the files (leaving them as buffers). If you're using the latest org-brain version, please post your org-brain related config.
