### ISSUE TITLE
What is the proper way to transform existing org fie to org-brain file?

### ISSUE THREAD

**Issue by BobCromwell** [Kungsgeten/org-brain#254]
I have some org files like below

> / brain_file_just_created.org  
> /work/ 1.org
> /work/...
> /work/ 1000.org
>/read/..

Thanks

**Comment by BobCromwell** [comment]
following ways works but not that convenience:
 
add  the file  as child of existing org brain headline, then using `org-id-get-create`  to add it to each entry in that file

**Comment by Kungsgeten** [comment]
Move the file to your `org-brain-path`. Now its an `org-brain` file. If you want to convert all the headlines in the file to entries, you could do `M-: (org-map-entries 'org-id-get-create)` in the file.

**Comment by BobCromwell** [comment]
@Kungsgeten Thanks!

**Comment by x-ji** [comment]
Seems that you now also have `org-brain-ensure-ids-in-buffer` if you want to convert all headlines in the file into entries, right
