### ISSUE TITLE
org-brain-rename-file does not change node name in labelled edges

### ISSUE THREAD

**Issue by swhalemwo** [Kungsgeten/org-brain#256]
Hi!
I've noticed that in the situation where I have node x and y as friends with an annotated edge, and then org-brain-rename-file node y to z, the #+BRAIN_EDGE_ line of node x does not get updated from #+BRAIN_EDGE_y: label to #+BRAIN_EDGE_z: label. Cheers!

**Comment by Kungsgeten** [comment]
Thanks, I hadn't thought about that. A problem here is that edge relationships aren't two-way. Something could have an edge to the file, without the file entry knowing about it. In order for it all to work nicely all entries would need to be scanned, which could take quite a long time I think.

**Comment by swhalemwo** [comment]
Do you think it would be possible to fix it for the cases where the edge relationships are two way? In the example above, the #+BRAIN_FRIENDS of x do get updated from y to z (I assume because the links of y are checked). These would then not requiring to scan all files, but only edit those which are already being modified by the rename command as it updates the node name. 

Also just out of interest (primarily for my visualization project where I use directed links by default), in which cases are edges not created both ways? I had the impression that friend links are always two way, and parent-child relationships as well as the nodes refer to each other as #+BRAIN_PARENTS and #+BRAIN_CHILDREN, respectively.

**Comment by Kungsgeten** [comment]
When adding an edge annotation you can use `C-u` to make the annotation one way. I don't know if anyone use it, but the idea is that you could annotate an edge from X -> Y but not have an annotation (or have a different one) from Y -> X.

Since `org-brain-rename-file` probably isn't used very often I guess it would be possible to just scan all `org-brain` files for edge annotations and replace them. It would be slow, but probably ok.

**Comment by swhalemwo** [comment]
ah I see you were talking about edge _annotations_. I'm indeed very happy about these one-way annotated edges since they allow me to indicate edge direction (I generally prefer directed edges). But even if the annotation is only one way (e.g. from x to y), there is still a two-way friend _relationship_ that could be used to rename the #+BRAIN_EDGE in x when y is renamed to z (I assume in the same way the #+BRAIN_FRIEND of x gets updated). The only edge annotations this would miss would be those where no edges existed (I've noticed that edge annotations don't get removed when an edge is removed, which maybe is a bug as well), but it would still be an improvement that wouldn't need to require scanning all files.

**Comment by Kungsgeten** [comment]
I don't quite understand what you mean. Just because you have a edge between two entries doesn't mean you got to have a friend relationship? Anyway I've made a commit which solves the issue (I hope).
