### ISSUE TITLE
Suggest add alias feature

### ISSUE THREAD

**Issue by tumashu** [Kungsgeten/org-brain#265]
a concept may have many concept name,  both of them may useful, what about add alias support？

**Comment by bepolymathe** [comment]
In your mind what would be the use? Be able to search it from different names in the same entry/file or more ?

**Comment by tumashu** [comment]
searching  from different names is a big feature,  sometime we may not realized two or more entries may very very similar thing, when i find this, we can set each other as alias, and show as a visual entry, for example (name1,name2), this is more simple than refile.

**Comment by bepolymathe** [comment]
Okay, I see. On my side, to group things together I prefer "friends" links and tags. But that doesn't invalidate your proposal. In such a situation, i prefer to use "tags" and org-ql which is very efficient to show input groupings by tags...

**Comment by tumashu** [comment]
now i use "friend" to deal with this problem, but i think is seem to not a better way

在 2020-03-01 17:34:56，bepolymathe <notifications@github.com> 写道：


Okay, I see. On my side, to group things together I prefer "friends" links and tags. But that doesn't invalidate your proposal. In such a situation, i prefer to use "tags" and org-ql which is very efficient to show input groupings by tags...

**Comment by Kungsgeten** [comment]
I think it might be possible to implement on headline entries, if using `org-mode` properties. It will be harder on file entries.

**Comment by Kungsgeten** [comment]
There's now "alias" functionality, but I call them "nicknames". You can add a nickname by pressing `N` in `org-brain-visualize`.
