### ISSUE TITLE
synchronize between multiple machines

### ISSUE THREAD

**Issue by ransomts** [Kungsgeten/org-brain#276]
I like to keep my org files synced using syncthing and would like to add brain to that folder.

When I copy my brain.org to the second machine I can see my headers in the helm select, but when I visualize the displayed item is the ID rather than the header name. In fact when I select something from the helm buffer the ID is inserted into brain.org as a header.

Any ideas of how to debug this? Or some way I can keep my brain.org consistent across my machines?

**Comment by Kungsgeten** [comment]
Hi! I use Dropbox to sync `org-brain` but I assume Syncthing works too (I haven't used it). `org-brain` uses `org-id` for the ID handling. `org-id` stores the IDs in a file, so you'll need to sync that file too. The path to that file is stored in the `org-id-locations-file` variable.

**Comment by ransomts** [comment]
Awesome that was it! Thanks for the speedy reply and great project!
