### ISSUE TITLE
Creating Headline Returns "Wrong number of arguments: (0 . 0), 2

### ISSUE THREAD

**Issue by dleszcynski** [Kungsgeten/org-brain#278]
Org-brain has been working fine until this morning. I tried creating a headline and I get the message: 
`org-brain-get-tags: Wrong number of arguments: (0 . 0), 2`
I've run org-brain-update-id-locations and am still getting the same thing. I have just begun the process of creating a custom init.el and so emacs is almost completely plain, out of the box. I haven't customized org-brain at all and have been using it fine until now. I have not been able to find anything specific to org-brain and this error online.

**Comment by Kungsgeten** [comment]
That's strange. Try running `M-x toggle-debug-on-error` and post the log here. Also see what `M-x org-version` says.

**Comment by dleszcynski** [comment]
Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Applications/Emacs.app/Contents/Resources/lisp/org/

Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 2)
  org-get-tags(nil nil)
  org-brain-get-tags(("Photography" "Journalism" "A6E348B9-D53E-40E8-9C29-360B174C4648") t)
  org-brain--vis-children(("Photography" "Journalism" "A6E348B9-D53E-40E8-9C29-360B174C4648"))
  org-brain-visualize(("Photography" "Journalism" "A6E348B9-D53E-40E8-9C29-360B174C4648"))
  #f(compiled-function (x) #<bytecode 0x43e17fb1>)(#<marker (moves after insertion) at 193 in *org-brain*>)
  button-activate(#<marker (moves after insertion) at 193 in *org-brain*> nil)
  push-button(507)
  funcall-interactively(push-button 507)
  call-interactively(push-button nil nil)
  command-execute(push-button)

I'm relatively new to emacs, so this is probably my fault, but thanks for your help!

**Comment by Kungsgeten** [comment]
`org-brain` requires `org-mode` version 9.2. I think `org-get-tags` was changed in version 9.2, so my guess is that is the reason it doesn't work.

We've all been new, no worries! Here's instructions on installing new org-mode versions: https://orgmode.org/elpa.html

**Comment by dleszcynski** [comment]
I knew that it was probably something simple. Thank you a million! I'm loving org-brain.
