### ISSUE TITLE
Add properties inside a file (not in visualize) with shortcut

### ISSUE THREAD

**Issue by lionelyoung** [Kungsgeten/org-brain#283]
When I'm inside a file, how do I add properties?  I have a lot of "dangling" headlines that are missing the properties, e.g.

```
  :PROPERTIES:
  :ID:       63319D6B-6462-4AC4-8903-B3EC72875282
  :END:
```

What I'm doing now is:

1.  open org-visualization
2. then hit "h"
3. Open the file, cut & paste the properties the the headline I want

Edit: I found `org-brain-add-child-headline` which gets close enough

**Comment by lionelyoung** [comment]
Edit: I found org-brain-add-child-headline which gets close enough

**Comment by lionelyoung** [comment]
This can add the ID to all blank headlines:
```
(defun add-id-to-all-headlines ()
  "Add org-id to all headlines"
  (interactive)
  (save-excursion
    (goto-char (point-max))
    (while (outline-previous-heading)
      (org-id-get-create)))

  )

```

**Comment by Kungsgeten** [comment]
You can now use `org-brain-ensure-ids-in-buffer`. I have personally added it to `before-save-hook`, so I don't have to run it manually.
