### ISSUE TITLE
visualize-follow opens new org-brain-visualize buffer in other window

### ISSUE THREAD

**Issue by alex-rozenshteyn-leapyear** [Kungsgeten/org-brain#287]
Steps to reproduce
1. Open an org-brain window
2. Turn on org-brain-visualize-follow
3. Click on a link

Expected result
* org-brain buffer moves to the link
* Link opens in another window

Actual result
* org-brain buffer moves to the link
* another org-brain buffer opens in another window, to the same location
* new window has focus
* if you press `q`, the correct buffer remains open

**Comment by Kungsgeten** [comment]
Should be fixed now. Thanks!
