### ISSUE TITLE
visualize shows link instead of description when headline contains a link

### ISSUE THREAD

**Issue by benjaminwd** [Kungsgeten/org-brain#288]
I have a few headlines that are also hyperlinks:

`* [[link][description]]`

This looks fine in org-mode, but org-brain-visualize shows the link portion rather than the description portion as the title of the entry when it should be the other way around. 
 
Note that I do want the link to appear in the resources as it does now.

**Comment by Kungsgeten** [comment]
Hmm, for me the description part is the name of the title in `org-brain-visualize`. Have you modified the variable `org-brain-headline-links-only-show-visible`, or is it `t` as per default?

**Comment by benjaminwd** [comment]
It is default. Changing it does show the complete formatting, link and description in brackets. Toggling it to standard shows only URL.

**Comment by Kungsgeten** [comment]
Sounds very strange. Could you post your configuration for org-brain, and a specific example of a headline which doesn't work?

**Comment by benjaminwd** [comment]
Thinking this might be an issue with some other package, I backed up my config and reinstalled emacs from the Ubuntu 18.04 repository and started clean and I'm still having the issue. A link like:

`* [[https://www.google.com][Google]]`

Will appear in org-brain-visualize as 

https://www.google.com
---Resources------
- Google

This is with no other packages and no custom configuration for org-brain at all (all default). The file I'm using is called: `~/org/brain/index.org` This is running 25.2.2 at the moment.

**Comment by benjaminwd** [comment]
An update: I jumped over to my Macbook which was running an older version of org-brain (20190830.757, I think) and emacs 26.1 from Homebrew and it was working  as expected. Once I updated to the newest version of org-brain in melpa using `package`, it introduced this issue (url showing instead of description).

**Comment by Kungsgeten** [comment]
If you're in `org-mode` and put the point/cursor over the heading and then type `M-: (org-brain-headline-at)`, what result do you get?

**Comment by benjaminwd** [comment]
It returned the link. In the case of my test file: "https://www.google.com". 

I tried reversing the [[Link][Description]] order: `[[Google][https://www.google.com]]` and it does make the link appear in org-mode and the description appear in visualize. It's like `org-brain-visualize` is reading the headlines the opposite order from org-mode.

**Comment by Kungsgeten** [comment]
I just noticed that I get the same behavior as you when updating to org-mode 9.3.6. My guess is that value of the regular expression that matches `org-mode` links has changed. I'll look into it!

**Comment by Kungsgeten** [comment]
I was correct in that the variable storing the regular expression matching an org-link had changed. Should be fixed now.
