### ISSUE TITLE
org brain edge not show to proper place

### ISSUE THREAD

**Issue by tumashu** [Kungsgeten/org-brain#290]
When  "B" have edge,  after I org-brain-visualize "B",  "B"'s edge will go to "A" or "C"

```
  A
  |
  B
  |
  C


```

**Comment by Kungsgeten** [comment]
I don't quite understand the problem. Is A the parent of B, and C is the child of B? With edges I assume you mean edge annotations? Are the annotations two-way? I think an `org-mode` example would make the problem more clear.

**Comment by tumashu** [comment]
I know the reason,   I misuse this feature, :-\

I use it to comment "B", while it should be used comment  the  connect of  "A<->B"

**Comment by Kungsgeten** [comment]
If you want to comment A -> B, instead of A <-> B, you can use the universal argument `C-u` before calling `org-brain-annotate-edge`. So in `org-brain-visualize` you could do `C-u e`.
