### ISSUE TITLE
Suggest a default description when completing brain links

### ISSUE THREAD

**Issue by Kungsgeten** [Kungsgeten/org-brain#292]
I don't know how to suggest default descriptions when using `org-link-set-parameters`. It would be nice thogh if `org-insert-link` could suggest the title of the entry when inserting `brain` links etc.

**Comment by randomwangran** [comment]
Thanks for maintaining `org-brain`. It helps me to build my secondary
brain but I am just an org-mode beginning user, not sure I can really
help something.

When I want to link a org-brain node in a plain text. This is how I do:

```
0. Launch `org-brain-visualize`
1. go to the location I want
2. C-c l `(org-store-link)`
3. exit *org-brain* buffer
4. mark the term that I want to link in the working file
5. C-c C-l `(org-insert-link)`
```

As you can see, I don't need to type the information about org-brain's
information.

When I write this response. I find something interesting.

If I want to insert a head line from a `whatever.org` file (index in
org-brain). I just:

```
1. launch `org-brain-visualize`
2. the searching the term I am interested in
3. find the term (headline in that whatever.org file)
4. `(org-store-link)`
5. close the `org-brain` buffer, and back to working buffer
6. C-c C-l `(org-insert-link)`
```

Then, hit <RET> for the latest link, like `brain:UUID`.

The title of that headline is inserted in my working org file.

Not sure I missing something here. Or, if I can help out anything.

Sorry for brothering you.

**Comment by Kungsgeten** [comment]
@randomwangran Yes it works fine if you insert a stored link. The problem is when using `org-insert-link` and typing `brain:` and pressing `TAB` to complete. When completing some extra things are done behind the scenes (like adding backlinks). Also if completing `brain-friend:` a friend relationship will be created, etc. In these cases it would be nice if the title of the completed entry could be suggested as a description.
