### ISSUE TITLE
How to add an org-store-link as a friend to a current entry?

### ISSUE THREAD

**Issue by dimitry12** [Kungsgeten/org-brain#294]
I am likely missing something very obvious, because I failed to figure out how to optimally perform the second most frequent (for me) use-case.

I want to be able to quickly add one entry as an org-brain "friend" of another entry directly from org-mode (or at least from org-brain-visualize-mode).

What I would expect:
- go to one entry, `M-x org-store-link`
- and:
  - either in org-brain-visualize-mode press `f` then `TAB` and see a stored org-mode link - but it's not there
  - or in org-mode `M-x org-brain-add-friendship` then `TAB` and see a stored org-mode link - but it's not there

Please, help me see what I am missing. Thank you!

**Comment by benjaminwd** [comment]
II generally use the autocomplete for this purpose:

In org-brain-visualize press `f` and locate the entry (you can use autocomplete from here: `brain_name::entry_name`)

In org-mode map a key or use `M-x org-brain-add-friendship` and use the same mechanism. You can also use helm-org-rifle for this purpose, though it's a bit of a different use case in my opinion.

**Comment by Kungsgeten** [comment]
Currently there is no functionality to use `org-store-link` in order to add relationships. Apart from the way @benjaminwd describes there's another way to add a friendship from `org-mode`:

If you use `org-insert-link` (bound to `C-c C-l` by default) you can insert a `brain-friendship` link, which will use completion among your current entries. Apart from inserting the link, it will also add a friendship relationship.

There's also another way to do it from `org-brain-visualize`. You can "select" an entry (or several) by pressing `s` (will select the entry at point, if there's a button). Then you can navigate the brain and where you want to add the friendship relationship you can press `S f` which will add all the selected entries as friends to the visualized entry.

**Comment by dimitry12** [comment]
@benjaminwd
> II generally use the autocomplete for this purpose

@Kungsgeten 
> If you use `org-insert-link` (bound to `C-c C-l` by default) you can insert a `brain-friendship` link, which will use completion among your current entries

@benjaminwd @Kungsgeten to make sure I understand your suggestions: in both cases I would need to autocomplete based on entry's heading, which I would need to "remember"?

> There's also another way to do it from `org-brain-visualize`. You can "select" an entry (or several) by pressing `s` (will select the entry at point, if there's a button). Then you can navigate the brain and where you want to add the friendship relationship you can press `S f` which will add all the selected entries as friends to the visualized entry.

That works! Except I have thousands of entries and relatively sparse graph at the moment. But I've just tested and I can:
- visualize entry A `M-x org-brain-visualize-entry-at-pt`
- select it with `s`
- exit visualization with `q`
- visualize entry B `M-x org-brain-visualize-entry-at-pt`
- add A as friend with `S f`
- unselect A with `s`
- exit visualization with `q`

I didn't realize selection is maintained  between activations of `org-brain-visualization-mode` - which makes the above process possible. Thank you!

**Comment by benjaminwd** [comment]
If you are a helm user you can use `helm-brain` to do this. This assumes all of these entries are in org-brain, but to add them as relationships they must be.

`M-x helm-brain`
Search for entry. `helm-brain` only searches headlines. Select multiple entries with `C-space`.
`tab` to get the menu and choose `select` (I can use `f7` on my machine, but I don't know if that's universal)
Return to the entry you wish to add the selected items to in `org-brain-visualize` 
Select `S-s` (that's a capital S if it's not clear from the syntax) to prefix the command you are about to run to use all selected entries
Run the command you wish to run (add children, friends, etc.)

I think there's an ivy option similar to this.

Side note, it would be nice to extend helm-org-rifle to have a similar option so we can use full text search to select entries. Beyond my capability, however.

**Comment by Kungsgeten** [comment]
@dimitry12 Actually you could do `M-x org-brain-select` directly from the `org-mode` buffer (with the point at the entry you want to select). Then you could go to the other entry in `org-mode` and use `M-x org-brain-add-selected-friendships`.

**Comment by dimitry12** [comment]
@Kungsgeten thank you! that's exactly the flow I was looking for: entirely in org-mode, and very efficient (+ `M-x org-brain-clear-selected` after interlinking everything I want to).
