### ISSUE TITLE
How to make org-brain not assume implicit relationships?

### ISSUE THREAD

**Issue by dimitry12** [Kungsgeten/org-brain#295]
org-brain assumes that parent-entry in my org-mode file is immediately a parent-relationship. That's quite opinionated. I am using journaling system with org-mode and my org-mode hierarchy is tangential to org-brain relationships.

How to make org-brain only visualize the edges which I explicitly created?

**Comment by benjaminwd** [comment]
You can either not give the entries org-ids or you can see if the special tags outlined in the readme will meet your needs.

I don't know your use-case, but I wonder if org-roam is not a better option since it's explicitly non-hierarchical.

**Comment by dimitry12** [comment]
@benjaminwd thank you!

> I don't know your use-case

I use timeline hierarchy, with "journal" entries as a primary mechanism of adding new notes.

> You can either not give the entries org-ids or you can see if the special tags outlined in the readme will meet your needs.

Good pointer. `:nosiblings:` might work for me - if I add it to my "journal"-template.

> I wonder if org-roam is not a better option since it's explicitly non-hierarchical.

Thank you - will check it out!

**Comment by Kungsgeten** [comment]
You could redefine the function `org-brain-entry-at-point-excludedp` and make it exclude entries based on some logic.

If you never want your journal to be part of your "brain" you could simply move the journal file outside of `org-brain-path`. You could still link to files inside `org-brain` from the journal using `C-c C-l` and if you have `org-brain-backlink` set to `t` you will get links back to your journal file.
