### ISSUE TITLE
Weirdness around renaming files with regex operators in file names

### ISSUE THREAD

**Issue by walseb** [Kungsgeten/org-brain#298]
Hi! So I have file entries with stuff like + and * in their name and creating them works fine but when I try to rename them things go wrong. For example renaming a file entry named: `a+` results in the old file relation not getting cleaned up, so if I started with 1 child relation I now have 2 but the new one just points to a non-existent file

**Comment by Kungsgeten** [comment]
Thanks for reporting this! Should be fixed now.

**Comment by walseb** [comment]
Great! Thanks a lot!
