### ISSUE TITLE
PINNED and HISTORY should be reset when switching to another brain

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/org-brain#302]
Otherwise, there are always errors while using obvz.

With reset in the title I mean cleared.  At least all entries coming from other brains should be removed.

**Comment by Kungsgeten** [comment]
This behaviour should already be implemented. If it doesn't clear history/pins it is a bug.

**Comment by michaelsjackson** [comment]
Ok, I could see, this problem is related to running obvz, however I can not find the source of the problem.

It behaves as follows:  When I switch to another brain, meaning directory or subdirectory for example, then somehow it complains of missing pins, from somewhere it still loads old pin entries, even I changed this file, run org-brain-update-id-locations, but still, it seems this updating mechanism does not help here, somehow.

If I look into org-brain-update-id-locations():
```

(defun org-brain-update-id-locations ()
  "Scan `org-brain-files' using `org-id-update-id-locations'."
  (interactive)
  (org-id-update-id-locations (org-brain-files)))

```
This seems to update only files, but not headers or do org-brain-files contain headers as well? Or asked in a different way, are the id's inside the files also updated?  Maybe this is the source of the problem, if those do not get updated?

**Comment by Kungsgeten** [comment]
The function which should reset the pins and history is
`org-brain-switch-brain`. I haven't tried obvz yet but I have it on my
TODO-list.

**Comment by michaelsjackson** [comment]
Yes, but the error appears, it suggests updating the id's, then I update, but nothing changes, still same error.  :-)

**Comment by Kungsgeten** [comment]
I see. If you get that error there's some kind of entry marker that can not be found. Try `M-x toggle-debug-on-error` and post the error log. Maybe I can find what's wrong :)

**Comment by Kungsgeten** [comment]
I noticed the error on my computer too. I'm not  sure why, but in the `.org-brain-data.el` file in the brain I tried to switch to there was information about pinned entries from the old brain. If I deleted this data before switching to the brain it all worked. The error might have been introduced in a previous version, or there might be something I've missed.

**Comment by michaelsjackson** [comment]
Yeah, something in this direction, interesting is, next day, trying again somehow it works again. If such error appears again, I can do your above suggestion and post again, thanks for your help.
