### ISSUE TITLE
behavior for childless entries containing headlines

### ISSUE THREAD

**Issue by dsteurer** [Kungsgeten/org-brain#312]
org-brain behaves in an unexpected way (to me) for childless entries
that contain headlines (and are not org-brain entries)

# example

``` org
* A                                                  :showchildren:childless:
  :PROPERTIES:
  :ID:       9cd26288-9f24-4321-82d2-37862bc00985
  :END:

** A1

** A2

* B
  :PROPERTIES:
  :ID:       76488493-993a-4be7-93fa-b9be8e1d6892
  :END:
```

# action

call org-insert-link from point A2 to add brain-child link from entry A to entry B 

# expected result

``` org
* A                                                  :showchildren:childless:
  :PROPERTIES:
  :ID:       9cd26288-9f24-4321-82d2-37862bc00985
  :BRAIN_CHILDREN: 76488493-993a-4be7-93fa-b9be8e1d6892
  :END:

** A1

** A2

[[brain-child:76488493-993a-4be7-93fa-b9be8e1d6892][B]]

* B
  :PROPERTIES:
  :ID:       76488493-993a-4be7-93fa-b9be8e1d6892
  :BRAIN_PARENTS: 9cd26288-9f24-4321-82d2-37862bc00985
  :END:
```

# actual result

funcall-interactively: Lisp nesting exceeds ‘max-lisp-eval-depth’

The reason appears to be that org-brain tries to use the id of A2
instead of its parent A. Since A2 doesn't have an id, things go wrong.

# backtrace (abbreviated)

the first error appears in the org-brain-add-relationship call with nil
provided for the first argument.

> Debugger entered–Lisp error: (error "Lisp nesting exceeds
> ‘max-lisp-eval-depth’")
> 
> org-brain-entry-name(nil) … org-brain-entry-name(nil)
> org-brain-entry-name(nil) (error "Couldn't find entry %s, try running
> org-brain-update-id-locations. " (org-brain-entry-name entry))
> org-brain–missing-id-error(nil) org-brain-entry-marker(nil)
> org-brain–linked-property-entries(nil "BRAIN<sub>CHILDREN</sub>")
> org-brain-children(nil) org-brain-add-relationship(nil ("test" "B"
> "76488493-993a-4be7-93fa-b9be8e1d6892"))
> org-brain-link-complete("brain-child")
> org-link–try-special-completion("brain-child") org-insert-link(nil)
> funcall-interactively(org-insert-link nil)
> call-interactively(org-insert-link nil nil)
> command-execute(org-insert-link)

# suggested fix

use property inheritance when looking up the id of the current entry.

the following version of org-brain–headline-entry-at-point appears to
fix the issue. (perhaps it is better to use buffer-file-name instead of
calling org-id-find-id-file.)

``` elisp
(defun org-brain--headline-entry-at-point (&optional create-id)
  "Get headline entry at point.
  If CREATE-ID is non-nil, call `org-brain-get-id' first."
  (if create-id (org-brain-get-id))
  (when-let ((id (org-entry-get (point) "ID" 't)))
    (list (org-brain-path-entry-name buffer-file-name)
          (org-brain-headline-at (org-id-find-id-in-file id (org-id-find-id-file id) 't))
          id)))
```

**Comment by Kungsgeten** [comment]
I think this should be fixed in the latest commit.
