### ISSUE TITLE
Preventing adding automatic ids to headlines for .org files in a given directory, required for Anki use case, but org-brain we need as well

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/org-brain#314]
I have this in my .emacs for automatically creating header id's when saving .org files, which is great for org-brain and obvz visualization of connections, also from headlines. So far great.

```
;; automatically add ids to saved org-mode headlines
(add-hook 'org-mode-hook
          (lambda ()
            (add-hook 'before-save-hook
                      (lambda ()
                        (when (and (eq major-mode 'org-mode)
                                   (eq buffer-read-only nil))
                          (eos/org-add-ids-to-headlines-in-file))))))

```

However, now I want to start using Anki and creating anki cards inside org-mode, I would like to disable this feature for .org files in a given directory, in my case in
`~/org`

So any .org file in above directory should not get any 
```
:PROPERTIES:
:ID:       f3d647fd-8679-43e7-8b74-12e46542e203
:END:
```
as they appear on the anki card, which I do not want of course.  In anki there should be just normal question and answer for learning those contents, plus images, but nothing related to properties.

Thanks in advance if you have any hints and tips.

**Comment by Kungsgeten** [comment]
I feel that this isn't related to `org-brain`, but Emacs in general. However maybe you could use `defvar-local` to make a local variable which is `t` by default, and check if it is true in your `before-save-hook` function. Then you can set it to `nil` in the files where you don't want to create IDs: https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html

**Comment by michaelsjackson** [comment]
Thanks for the hint, now I need to learn elisp quickly, how to do if then else checking., without breaking anything available so far.  I should read some Xah Lee tutorials probably.  :1st_place_medal:

**Comment by michaelsjackson** [comment]
I guess I need to use something like
```
(if something
    (progn ; true
    …
    )
    (progn ; else
    …
    )
)
```

I am looking for the quickest solution without having to read the entire elisp manual first.  :100: 

Probably this below is wrong.
```

;; automatically add ids to saved org-mode headlines
(add-hook 'org-mode-hook
          (lambda ()
            (add-hook 'before-save-hook
                      (lambda ()
                        (when (and (eq major-mode 'org-mode)
                                   (eq buffer-read-only nil)
                                   (eq defvar-local t)      ;; added new for testing
                                   )
                          (eos/org-add-ids-to-headlines-in-file))))))
```

**Comment by Kungsgeten** [comment]
It can be cumbersome to learn a new programming language, and Emacs Lisp is a bit strange at first. Unfortunately I do not remember how I first learned it. Here's what I'd do:

```
(defvar-local add-org-ids-on-save t)

(add-hook 'before-save-hook
          (lambda ()
            (when (and (eq major-mode 'org-mode)
                       (not buffer-read-only)
                       add-org-ids-on-save)
              (eos/org-add-ids-to-headlines-in-file))))
```

**Comment by michaelsjackson** [comment]
Thanks my friend, seems to work, will test more tomorrow. Great.  If this works well, then I only need to find a best solution for images in Anki. (for both, org_to_anki  and anki-editor), if above solution works at least images in anki-editor would look properly, without properties each time. Thanks again.
