### ISSUE TITLE
Visualize shows different link text from that in the org file

### ISSUE THREAD

**Issue by codingquark** [Kungsgeten/org-brain#315]
Attaching screenshot

![err_org_brain](https://user-images.githubusercontent.com/456712/83487190-32263280-a4c8-11ea-8efd-7b5a32ff6a1c.png)

My `:RESOURCES:` entry is: `[[http://git.savannah.gnu.org/cgit/emacs.git/commit/etc/NEWS?id=7f692114cdc983cc04b05dd31d3119d0f48c38d3][malayalam_support_emacs_devel]]` which is displayed as `malayalam` in visualize buffer.

**Comment by Kungsgeten** [comment]
Thanks for reporting this! Strange bug since it worked if you replaced the underscores in the description with spaces. Anyway it should be fixed now.

**Comment by codingquark** [comment]
After updating from melpa to `20200602.741` this is a new behavior. Attaching screenshot:

![capture](https://user-images.githubusercontent.com/456712/83534133-18a7d980-a50e-11ea-9e4b-106bfc8e8601.png)

Now, the link description shown in the visualize buffer is from a different entry in the same `recipes.org` file (`Banana Beer`). The link it opens is the right one (that of kvass, as linked in the resources).

**Comment by Kungsgeten** [comment]
Yes I noticed this too :) I think it is fixed already if you update to the latest version. I just fixed it a couple of minutes ago though, so I don't think its up on MELPA yet.

**Comment by codingquark** [comment]
Confirmed fix. Thanks and sorry for the bother!

**Comment by Kungsgeten** [comment]
No problem at all! I'm now intrigued about trying to make kvass (hadn't heard about it before). I don't drink alcoholic beverages though, but perhaps trying this could be an exception :)

**Comment by codingquark** [comment]
There is at least one person on `#emacs` achieving mastery in making kvass without any alcohol but all the taste.

**Comment by drawkula** [comment]
\o/
What about an org-brain example (text or brain) with exactly this recipe?

**Comment by codingquark** [comment]
@drawkula very low concentration after 30h. I kept the yeast around in storage container to get a bit more concentration. Taste was that of lemonade. :)
