### ISSUE TITLE
Symbol's function definition is void: mapcan

### ISSUE THREAD

**Issue by bmgxyz** [Kungsgeten/org-brain#318]
Hi there:

I'm really excited to try out `org-brain`, since it looks really cool, but I'm having some trouble getting it running. Whenever I try `M-x org-brain-visualize`, I get this error:

```
Symbol's function definition is void: mapcan
```

I'm essentially clueless when it comes to `emacs`, so I'm sure this is something simple. It looks like `mapcan` is a pretty fundamental function in Lisp, and it only appears twice in this repo, so I'm not sure how it could be missing or undefined. Other parts of the Internet haven't been helpful for me so far.

If it helps, I'm running `emacs` 25.1.1 on Debian 9 Stretch and `org-mode` 9.3.6. I think I've got a sane setup here, including a lightly modified version of the listing in the `README`.

Thanks for any help you can provide and for building such a neat-looking bit of software.

Bradley

EDIT: Also, I appear to be running the latest `org-brain` as of writing, which I believe is 20200603.1650.

**Comment by Kungsgeten** [comment]
In my Emacs `mapcan` is a built-in C function. However I'm using Emacs 26.3 and it seems like `mapcan` was introduced as a built-in in version 26. I should probably update the required Emacs version. You could try though to put `(require 'cl)` in your config before loading `org-brain`, since I think `mapcan` was defined there before.

**Comment by bmgxyz** [comment]
Adding `(require 'cl')` just before `org-brain` gets loaded in my config seems to have fixed it. I can now at least add an entry, which I'm going to assume is a good metric for `org-brain` functioning properly.

Thanks for helping me. Up to you whether or not you want to add a note about `(require 'cl')` for Emacs 25, but since my issue is resolved I'll go ahead and close this.
