### ISSUE TITLE
condition-case: Symbol’s value as variable is void: org-brain-poly-hostmode

### ISSUE THREAD

**Issue by spacekitteh** [Kungsgeten/org-brain#319]
After adding the `polymode` hook in `org-brain`'s `use-package` declaration, `org-brain-visualize` throws this error. It occurs in both emacs 27 and 28.

**Comment by Kungsgeten** [comment]
When do you get this error and have you changed your configuration in some kind of way? `org-brain-poly-hostmode` shouldn't be used unless you're using `polymode`.

**Comment by spacekitteh** [comment]
Sorry, I thought I added that info.

**Comment by spacekitteh** [comment]
Ok, it only happens when the `:hook` declaration is specified as part of `(use-package org-brain ...)`.

**Comment by spacekitteh** [comment]
Ok for some reason it works now after deleting all my .elc's.
