### ISSUE TITLE
Often, using or navigating brain kills clipboard contents

### ISSUE THREAD

**Issue by pangloss** [Kungsgeten/org-brain#338]
This may only happen if an entry has "friends", but it's unacceptable any time because clipboard data may be valuable and should never be silently destroyed without user interaction with a reasonable expectation of clipboard changes.

Currently org-brain has put a string with 50 spaces into my clipboard...

I really like org-brain, btw, great work overall! :)

**Comment by Kungsgeten** [comment]
I agree! I haven't thought about this before. I think the culprit is the function `kill-whole-line` which is used quite a bit by `org-brain`. I haven't found a replacement for it which doesn't push to the kill ring, but I'll look into it.

**Comment by Kungsgeten** [comment]
I think this should be solved with the latest commit. Thank you for reporting this, and for your kind words!
