### ISSUE TITLE
Exclude entire file from org brain

### ISSUE THREAD

**Issue by Jdude311** [Kungsgeten/org-brain#341]
Is it possible to exclude an entire file from the org brain? I know that you can exclude a subtree, but can you exclude a file and all of its headings?

**Comment by Kungsgeten** [comment]
Hi! I haven't tried it, but see if setting one of the exclude tags on the
file does the trick. Otherwise it would be easy to move the file outside of
your org-brain-path, but that may mess with relative links if you have any.

**Comment by pmnerfed** [comment]
won't it work if you add  `#+filetags: nobrain` or any other tag that is part of your `org-brain-exclude-tree-tag`.

Edit: is the issue too old to be marked as closed?

**Comment by Jdude311** [comment]
Hey everyone, sorry about this, I made this a long time ago and completely forgot that I asked. I knew a lot less about EMACS back then lol. I'm marking it as closed because I a) don't use org-brain anymore, as it doesn't fit what I currently need (I'm using org-roam at the moment) and b) since using filetags should work (I did not know they existed when I asked this).
