### ISSUE TITLE
Is there a hook that can be used to run functions after clicking on the entry in Org-brain Visualize mode?

### ISSUE THREAD

**Issue by randomwangran** [Kungsgeten/org-brain#344]
Now, I write two advice to `push-button` and
`org-brain-visualize-back` to achieve this as the following code
snippet.

    (advice-add 'push-button :after
                (lambda (&rest _)
                  ...))
    
    (advice-add 'org-brain-visualize-back :after
                (lambda (&rest _)
                  ...))

I was wondering if there is a more elegant solution?

Thank you.

**Comment by Kungsgeten** [comment]
There is a hook named `org-brain-after-visualize-hook`, but I'm not sure if that's what you need. What are you trying to do?

**Comment by randomwangran** [comment]
I would like to use `(org-brain-after-visualize-hook)` to show inline images.

I've tried the following code without success:
```elisp
(advice-add 'org-brain-after-visualize-hook :after
            (lambda (&rest _)
              (org-redisplay-inline-images)))
;; or
(advice-add 'org-brain-after-visualize-hook :around
            (lambda (&rest _)
              (org-redisplay-inline-images)))
```
But is able to do that using the following code:
```elisp
(advice-add 'push-button :after
            (lambda (&rest _)
              (progn
                 (org-redisplay-inline-images)
                 (message "running push-button hook to show inline images for org-brain"))))

(advice-add 'org-brain-visualize-back :after
            (lambda (&rest _)
              (progn
                (org-redisplay-inline-images)
                (message "running org-brain-visualize-back hook to show inline images for org-brain"))))
```

**Comment by Kungsgeten** [comment]
Okay, then `org-brain-visualize-text-hook` should work, I think.

**Comment by randomwangran** [comment]
Life saver! Thank you.
