### ISSUE TITLE
[Suggestion] file + line number resource

### ISSUE THREAD

**Issue by rakanalh** [Kungsgeten/org-brain#347]
Hi

I just started using org-brain through doom-emacs and i have a couple of suggestions related to the same thing:

1. Add the ability to link to a file with a reference to line numbers. 
A good use case for this is when studying a codebase, trying to create a mind map of the files and code locations for entries.

2. I noticed that org-capture also prompts if i wanted to add a brain-entry as one of the options. Selecting "todo" from that prompt would add an empty entry attaching the filename and the place (line) at which i invoked the command. Doing that in org-brain and placing the location from which i invoked org-capture (brain) would be great as well.

**Comment by Kungsgeten** [comment]
Hi!

1. `org-mode` already supports linking to line numbers in files, see here: https://orgmode.org/manual/External-Links.html
2. I think that is possible if you change the capture template, but I'm not 100% sure.

**Comment by rakanalh** [comment]
Thanks... You're right. Apparently i can use `file:///{filename}:NNN` pattern to point to a specific file number.

Also for the record, i have updated `org-capture-templates` for `org-brain` as follows:

```
(after! org-brain
  (cl-pushnew '("b" "Brain" plain (function org-brain-goto-end)
                "** %i%?\n:PROPERTIES:\n- %a\n:END:\n" :empty-lines 1)
              org-capture-templates
              :key #'car :test #'equal))
```
