### ISSUE TITLE
Fail to create links between headline entries

### ISSUE THREAD

**Issue by tristanstoeber** [Kungsgeten/org-brain#349]
Dear Org-Brain developers,
for some reason org-brain does not allow me to create links between headline entries. I assume this is not the desired behavior? Any help would be appreciated.
My org brain version is 20200316.2105
Best,
Tristan

**Comment by Kungsgeten** [comment]
Hi! What kind of links are you trying to create, and what kind of error message do you get?

**Comment by tristanstoeber** [comment]
Hey Kungsgeten, thanks for the immediate answer, I was trying to create a friend link between two headlines. Pressing "f" showed all other entries execpt those within the same file.
However, now after installing the current version from the repo and not from melpa it is possible to add links between headline entries.

**Comment by Kungsgeten** [comment]
Okay, strange that the MELPA version was so old. Happy to hear that it works now!
