### ISSUE TITLE
Could I use org-brain in a path-independent manner?

### ISSUE THREAD

**Issue by drcxd** [Kungsgeten/org-brain#367]
I am looking for a tool which could convert a org-mode file to something like a mind map.

I have found [org-mind-map](https://github.com/the-ted/org-mind-map) and [org-graph-view](https://github.com/alphapapa/org-graph-view). They are, however, not in active maintenance.

Then I found org-brain. It has many advantages comparing to the other tools. First it's an online tool, I mean, I could easily edit my org file and see the results in `org-brain-visualize` rather than converting org file to another file. Second, I could jump into anywhere in the org file from the `org-brain-visualize` buffer.

However, I could not find a way to use org-brain in a path-independent manner. I mean, I have to put every org file into a particular path, if I want to visualize it using org-brain. Is there anyway I could just open a random org file located in anywhere, and then visualize it using org-brain? Of course, org-brain could only use headlines as entries, but this suffices in many situations.

After a second thought, I think it is still good to limit a brain in a certain path. However, could you apply a pattern like git? I mean, each brain is like a repository or a project. At the root of each brain, a folder named like `.brain` could be used to store all the meta data of the brain. Currently, I saw the pinned nodes are stored in a local file. However, information like history is stored globally.

**Comment by Kungsgeten** [comment]
Hi! No, there's no functionality to visualize a single file. The closest thing would be to use `M-x org-brain-switch-brain` and visualize the directory containing the file. This, however, creates an org-brain datafile, which adds some clutter to your directories.

**Comment by michaelsjackson** [comment]
Hey drcxd, did you try obvz?
https://github.com/swhalemwo/obvz

You might like it. It can export the mind maps as .svg or .png for example. You have various settings like show a few more sentences for each entry in your mind map or not. Showing the edge labels or not for example.

**Comment by drcxd** [comment]
> Hi! No, there's no functionality to visualize a single file. The closest thing would be to use `M-x org-brain-switch-brain` and visualize the directory containing the file. This, however, creates an org-brain datafile, which adds some clutter to your directories.

Thanks for the answer. I am quite satisfied with how `org-brain` currently works while I am getting more and more familiar with it. Could you consider my suggestion of creating something like `.git` in the brain directory to store metadata, including pinned nodes, history or anything is related to the brain in question?

Finally, thanks for creating such a terrific productivity tool in emacs. I like it so much.

**Comment by drcxd** [comment]
> Hey drcxd, did you try obvz?
> https://github.com/swhalemwo/obvz
> 
> You might like it. It can export the concept maps as .svg or .png for example. You have various settings like showing a few more sentences for each entry in your concept map or not. Showing the edge labels or not for example.

Thank you for the heads-up. I just read the README file and it would be a good add-on for `org-brain`.

**Comment by michaelsjackson** [comment]
Just use both together. Working nicely here. I would recommend changing colors a bit. Then all looks more interesting imo.

**Comment by Kungsgeten** [comment]
> Thanks for the answer. I am quite satisfied with how `org-brain` currently works while I am getting more and more familiar with it. Could you consider my suggestion of creating something like `.git` in the brain directory to store metadata, including pinned nodes, history or anything is related to the brain in question?

`org-brain` already stores a data file including some meta data. It is named `.org-brain-data.el`.
