### ISSUE TITLE
single document use-case

### ISSUE THREAD

**Issue by oatmealm** [Kungsgeten/org-brain#375]
I know this is not the intended use-case, but I'm wondering if it's possible to restrict `org-brain` to only work on the currently active document? i.e. all available actions will only query heading in the document from which they're invoked...

**Comment by Kungsgeten** [comment]
Hi! No, there's no such functionality at the moment. It would be interesting to hear about the use case.

**Comment by oatmealm** [comment]
I have something implemented this way, so far. It's based on the idea that a document I'm working on is placed in it's own directory somewhere.

![Screenshot from 2021-11-30 10-27-26](https://user-images.githubusercontent.com/68159077/144021004-7663dbb5-0901-462f-8cd1-aad2edbf9a89.png)

Where the document has this local variables set for the document. It's generic, so can be used in a template I guess.

```
* Meta :nobrain:
# Local Variables:
# eval: (setq org-brain-path default-directory)
# End:
```

Seems to work. Plus if the document's sub-directory is placed in the global org-brain-path, then I could link to this document, but clearly not the other way around, which I'm thinking, might be useful.

**Comment by Kungsgeten** [comment]
Okay, I see. I think you could simply put the document in its own (sub)folder and use `M-x org-brain-switch-brain` to choose that folder. I haven't used multiple brains much myself though, and it was quite some time since I implemented the feature.

**Comment by oatmealm** [comment]
Oh, OK, I missed that :) I'll give it a try. Is there a mechanism to link two "brains" as well?

**Comment by Kungsgeten** [comment]
You could use the brainswitch link in the body of an entry. Search for it in the README :)
