### ISSUE TITLE
help needed: enabling org-cite/citar actions in visualized buffer

### ISSUE THREAD

**Issue by oatmealm** [Kungsgeten/org-brain#376]
Hi. Wondering if you might be able to help with this issue? https://github.com/bdarcus/citar/issues/445

The idea is to have citar's *-dwim actions (or org-cite) to work while in an `org-brain`  buffer.

The screenshot is of embark action on a cite, which in org-mode buffers would offer some relevant action available for cites.

![Screenshot from 2021-11-28 19-36-13](https://user-images.githubusercontent.com/68159077/143785591-a5b5f88e-82a9-4e03-b7ce-7bc483459734.png)

**Comment by bdarcus** [comment]
Just to clarify, citar runs its embark org-cite target finders in org derived modes only.

Is it practical for you to have this visualization mode derive from org?

**Comment by Kungsgeten** [comment]
I'm sorry but I don't quite understand the issue. I've tried citar, but not in combination with org-brain so far.

**Comment by bdarcus** [comment]
We figured out a workaround, which is just having @oatmealm add an entry to `citar-major-mode-functions` so that the at-point functions would run in the visualize buffers.

He was just having a problem because the citations were highlighted, he couldn't access the embark menus from them, as he can in org proper.

**Comment by oatmealm** [comment]
On top of that, my issue was that while browsing the visualized buffer (I was planning to give a presentation using it).  

I'd like to open/follow a reference and go back to the visualized buffer when done, so I t seems to make sense to have citar at-point functions active/available for this purpose.

**Comment by Kungsgeten** [comment]
Happy to hear you managed to find a solution!
