### ISSUE TITLE
[Q] org-brain-ensure-ids-in-buffer respecting a :noid: tag would be nice

### ISSUE THREAD

**Issue by drawkula** [Kungsgeten/org-brain#378]
`org-brain-ensure-ids-in-buffer` respecting a `:noid:` tag would be nice?

Headings without an `ID` don't appear in `org-brain`'s view.  I like to use that to wrap stuff for plain `org-mode` (org options, export settings, header-args, ...) in it as `* preamble` and `* postamble`,  but sometimes using `org-brain-ensure-ids-in-buffer` would be nice in my workflow. It then would give those sections `ID`s too.

Is (ab?)using ID-less sections as hidden ones for `org-brain-visualize` a silly idea?
Are there better ways?

If not, would making `org-brain-ensure-ids-in-buffer` break other things?
Would you use it too?

**Comment by Kungsgeten** [comment]
Hi! If I understand correctly you could use the `:nobrain:` tag on the headlines that you want to exclude from the brain.

**Comment by drawkula** [comment]
Epic oops moment!  
I was constantly overlooking that one.
\o/

[huge] THANKS! [!-- no end tag ;-) --]
