### ISSUE TITLE
Opening an entry instead creates a new file named after entry ID

### ISSUE THREAD

**Issue by Wheest** [Kungsgeten/org-brain#380]
My apologies if this issue already exists, it's quite hard to concisely describe, and I could not find other issues related to it.

I just moved to a new machine, and moved over my org-brain library.  I am using Doom Emacs, and my config.el for org-brain matches the one in this repo's README, though I use counsel-brain with `:bind (("C-c b" . 'counsel-brain))`.  This is the same config I had on my old machine.

If I run `C-c b`, I can navigate my various org-brain entries, however if I attempt to open the entry, the org-brain visualise interface appears, however shows an empty entry with the name matching the org-id of my chosen entry (e.g. 
2daaeb60-8c…).  However, it also creates a new file in my org-brain directory called `2daaeb60-8c….org`.

Any idea what could be causing this?

**Comment by Kungsgeten** [comment]
My guess is that the org ids aren't synced to your new machine. Try running M-x org-brain-update-id-locations

**Comment by Wheest** [comment]
Ah many thanks, that was the issue!

Org-brain is super useful to me, is there a donation link or similar?  Or a recommended upstream project that should get it?

**Comment by Kungsgeten** [comment]
I'm glad you enjoy the package and find it useful! I've gotten out of the habit of using it myself, but will hopefully start again. I don't have a donation link, but I'd suggest supporting Org-mode directly by donating to Bastien Guerry @bzg the maintainer of Org-mode. More info here: https://orgmode.org/contribute.html

**Comment by bzg** [comment]
Thanks for sharing this URL @Kungsgeten!

It is worth mentioning that donations now go to the group of Org co-maintainers, not just me.

We also welcome maintainers of packages from the Org ecosystem, so feel free to share your Liberapay username and we will add you on https://liberapay.com/org-mode/.
