### ISSUE TITLE
Can't add new nodes to the brain

### ISSUE THREAD

**Issue by lucasemmoreira** [Kungsgeten/org-brain#383]
Hi there, awesome software you have!

But I am having some issues with it, although I am confident these are user mistakes. 

I had a brain and I did a few tests with it, but after I got a grasp of it I wanted to start a new one. That's when things went south. Every time that I try to start new brain, I cannot manage it. Here is an error that I get:

```
Added ’’ as a child of ’’.
```

I assume this is because org-brain is lost regarding the ids in my machine but I am not sure how to fix it.

Note: I tried to "start over" by deleting the whole folder (including .org-brain-data.el) and the .org-id-locations. Not sure if there is another file to be deleted.

Any help is appreciated!
Cheers!

**Comment by vedang** [comment]
Try `M-x org-brain-update-id-locations` and see if it helps.

**Comment by lucasemmoreira** [comment]
No luck. It find some files but org brain is still lost. First I get this message:
```
8 files scanned, 5 files contains IDs, and 5 IDs found.
```

But when I try going into the pinned entry, it is all blank. And when I try to refresh it with `g` this is the message I get

```
org-brain--missing-id-error: Couldn’t find entry mba-icmc::mba-icmc, try running org-brain-update-id-locations. 
```

I wouldn't mind start the brain from scratch, I just don't know how to.

**Comment by lucasemmoreira** [comment]
I may have find out a solution.
I had a default header every time I created an org mode.  Something like:
```
#+Title:
#+Author: author-name
#+mail: an mail
```
Hence, all my brain files had this header. As I removed them from the files and from the new ones to be created, org brain works smoothly.

Not sure if this makes sense, but making notes for anyone who might face similar problems
