### ISSUE TITLE
Is it possible to display all hierarchical under visualize-mind-map?

### ISSUE THREAD

**Issue by Prague2049** [Kungsgeten/org-brain#393]
Under normal mode,  all hierarchical could be showed as follow:
 
<img width="324" alt="image" src="https://github.com/Kungsgeten/org-brain/assets/86907530/64141b93-537a-4907-b4a1-9c940916e277">
Under normal mode, only two level could be showed as follow:
<img width="374" alt="image" src="https://github.com/Kungsgeten/org-brain/assets/86907530/b88ccf25-0e9e-4c45-8257-7aed78a46651">
Is it possible to display all hierarchical under visualize-mind-map?

**Comment by Kungsgeten** [comment]
Sorry for the very late response. I'm not sure if I understand the quiestion, but I'll try: In the mind map mode it is possible to "zoom in/out" to show more of the hierarchy. That isn't possible in the normal visualize mode though (because of the more complex graphical rendering).
