### ISSUE TITLE
Create parent directory?

### ISSUE THREAD

**Issue by tumashu** [Kungsgeten/org-brain#4]
```
directory-files-recursively: Opening directory: No such file or directory, c:/msys32/home/feng/org/brain
```

**Comment by Kungsgeten** [comment]
Hmm, I thought that the code would create parent directories. Could you please provide some more information about what you tried to do?

**Comment by tumashu** [comment]
When directory "org-directory" is not exist,  org-brain-open can't work well.

**Comment by tumashu** [comment]
When I delete "~/org/brain/" directory,  org-brain-open shows:

```
directory-files-recursively: Opening directory: No such file or directory, c:/msys32/home/feng/org/brain
```
c:/msys32/home/feng is "~"

In my opinion, "~/org/brain/" should be created when run org-brain-open, if it doesn't exist

**Comment by Kungsgeten** [comment]
I see! Thanks for explaining. Should be fixed now (I hope).
