### ISSUE TITLE
 (org-brain-activate-cache-saving) error

### ISSUE THREAD

**Issue by jiagoumengxiang** [Kungsgeten/org-brain#44]
missing  (interactive) ?

**Comment by Kungsgeten** [comment]
It is really meant to be included in your init-file, since otherwise you would have to run it each time you start Emacs. Adding it as an interactive command would just add extra clutter?

**Comment by Kungsgeten** [comment]
`org-brain-activate-cache-saving` is deprecated since version 0.4, since `org-mode` doesn't use its own cache saving anymore.
