### ISSUE TITLE
Brain-visualize stealing focus

### ISSUE THREAD

**Issue by rsuhada** [Kungsgeten/org-brain#5]
After I activate brain-visualize, after some time (not immediately) it starts to steal focus from any other buffer after some time. I.e. no matter in which buffer am I, brain-visualize opens up and takes the point away from its current focus and puts it onto the central topic in the map.

Killing the visualize buffer doesn't help - it still returns and continues stealing focus. The only way out is to restart emacs (and not run brain-visualize)

I have no idea what could be the reason here. Do you have an idea what could be the issue here?

**Comment by Kungsgeten** [comment]
This has happend to me too. At first it happend when I had a buffer opened, whose file had changed on disc. Now it still happens sometimes, but I'm not sure why either. I'll try to investigate, and if you make any more discoveries, do tell.

**Comment by rsuhada** [comment]
It seems that it is the `(goto-char entry-pos)` function inside `org-brain-visualize`. 
If I comment it out it seems to work ok (except the point is not recentered on current topic).
Maybe wrapping it into a condition to be run only if current-buffer is *org-brain*?

**Comment by Kungsgeten** [comment]
I've commited a change that hopefully fixes the problem (but its a bit hard to test since the problem doesn't happen all the time). Please try it out. I believe the problem may have been the `pop-to-buffer` function, combined with reverting the buffer.

**Comment by rsuhada** [comment]
Haven't yet time to test it thoroughly, but up to now looks very promising! Thank you!

**Comment by Kungsgeten** [comment]
I'm closing this since I haven't noticed any problems since the fix. Please reopen it if the problem still occurs.
