### ISSUE TITLE
Feature: Export Relationship to CSV/TSV

### ISSUE THREAD

**Issue by fuxialexander** [Kungsgeten/org-brain#50]
Will it be possible to export all node/relationship into one/several tab-delimited file like:
Node.txt: {NodeID, NodeTitle, NodeResources(optional)}
Relationship.txt: {NodeID, ParentID, ChildID, FriendID}
The schema can change as long as structure and title information is preserved.
If that's possible, maybe I can explore to write a web-page based visualizer using D3.js (http://bl.ocks.org/robschmuecker/7880033).

**Comment by Kungsgeten** [comment]
I guess this should be possible to do. I'm not quite sure I understand what each row of the CSV output would represent though. The idea is that one file holds all entries, and the other all relationships (with a new line for every relationship)? If so, how would the second file look?

Let's say I have three entries. Node.txt (ignoring resources):

```
0, Text editing
1, Emacs
2, Org-mode

```
Relationship.txt

```
0, , 1,
0, , ,2
1, 0, ,
1, , 2,
2, 1, ,
2, , ,0
```
This is a bit cryptic to read, but the idea was `Text editing` -> `Emacs` -> `Org-mode` and that `Text editing` and `Org-mode` were friends.

**Comment by fuxialexander** [comment]
Yes I think the format in your example is OK. We can perform a one-pass parse of the second file to reconstruct the network in javascript, and visualize it. The first file will simply serve as a dict for name retrieval.
Of course, if we encode each relationship in one line, we could also consider use a more compact representation like the following:
source, target, relationship
0, 1, child (could be encoded as 0/1/2/... also)
0, 2, friends

Anyway, as long as there is a fixed format with covers all information, it's gonna be OK. We can write the parser accordingly.

**Comment by azzamsa** [comment]
> maybe I can explore to write a web-page based visualizer using D3.js

Hope it can be implemented. I think sharing our *brain* to other is awesome :)

**Comment by Kungsgeten** [comment]
@fuxialexander I've started a new repository named [org-brain-export](https://github.com/Kungsgeten/org-brain-export). I think discussions focused on exporting could be moved there. A starting point could be: https://github.com/Kungsgeten/org-brain-export/issues/2

I'm closing this since I think export discussions could take place there.
