### ISSUE TITLE
Resources links include line breaks

### ISSUE THREAD

**Issue by DiegoVicen** [Kungsgeten/org-brain#51]
It seems that org-brain is able to detect automatically the links inside the of the notes (which is a super cool feature). However, I like to use `auto-fill` mode to wrap the lines at 79 characters, so sometimes I have line breaks in those links. For example, in this note:

<img width="620" alt="screen shot 2017-06-26 at 23 26 35" src="https://user-images.githubusercontent.com/7013448/27561177-6bd7d4f0-5ac7-11e7-9ee7-6374f136825b.png">

I get this result when using `org-brain-visualize`:

<img width="547" alt="screen shot 2017-06-26 at 23 26 59" src="https://user-images.githubusercontent.com/7013448/27561205-87fb814a-5ac7-11e7-8bd3-d6dbbee026e7.png">

I'm not sure if this is the desired behavior for the resources, but I think it looks a bit off. Is this a problem my configuration or it is actually an `org-brain` bug/feature?

**Comment by Kungsgeten** [comment]
Hi! Good catch! `org-brain` just fetches the text of the link (using `org-element`) and apparently this includes linebreaks. I've commited a fix, thanks!
