### ISSUE TITLE
duplicate entry 

### ISSUE THREAD

**Issue by sunwayforever** [Kungsgeten/org-brain#54]
the original org file:

`#+BRAIN_CHILDREN: 9f9b95a6-439f-4332-8e9a-02c789a9b2ef

* Test

* a
:PROPERTIES:
:ID:       9f9b95a6-439f-4332-8e9a-02c789a9b2ef
:BRAIN_PARENTS: test
:END:
`

after visualize:

`PINNED:

test

a  a  `

**Comment by Kungsgeten** [comment]
Thanks for reporting this! I'll try to fix it ASAP (on vacation at the moment). The reason is that a is a local child of test (the file), but you've also added it as an external child.

**Comment by Kungsgeten** [comment]
Should be fixed now
