### ISSUE TITLE
org-brain-visualize doesn't autoload

### ISSUE THREAD

**Issue by perfectayush** [Kungsgeten/org-brain#56]
Hi,

Since changes for version 0.4, the org-brain-visualize doesn't autoload anymore. Can we fix that?
It's resulting in spacemacs fail to call org-brain-visualize via keyboard binding for the first time in a new session. I have to explicitly load org-brain.

Also, thanks for this neat package.

**Comment by Kungsgeten** [comment]
Hi! I've forgotten to add an autoload cookie for that function. I'm on vacation at the moment, but I'll try to fix it ASAP. You could also send a pull request if you want, it is just one line of code.
