### ISSUE TITLE
Feature: exporting org-brain relationships as links

### ISSUE THREAD

**Issue by namdnguyen** [Kungsgeten/org-brain#58]
It would be great to be able to export org-brain relationship properties as links in HTML, PDF, or ODT exports. Maybe the related links could be listed under subheadings like "related" or "see also," depending on the kind of relationship. 

Another option for exporting that could be specified is to convert them to #+INCLUDE links before exporting, which would include the body of the entry being linked instead of just a link.

**Comment by Kungsgeten** [comment]
Some sort of exporting would certainly be nice. My main concern has been that it doesn't really make sense to only export one of your `org-brain` files, you'd probably want to export them all. It might be possible to add "external relationships" (relationships which aren't a direct parent or child in the same file) as links, in the way you describe.

Another I've had is to be able to export into a single giant HTML file, similar to TiddlyWiki.

I think the best way of doing an export feature would be to use the `org-mode` [publishing feature](http://orgmode.org/manual/Publishing.html). My guess is that an export feature would take quite a lot of work, and I'll probably not work on it in the near future. If anyone else would like to have a go at implementing such a feature; feel free to contact me if you need help.

**Comment by azzamsa** [comment]
> Another I've had is to be able to export into a single giant HTML file, similar to TiddlyWiki.

I think it's everyone's dream :)

I hope (in near future) we can export the brain to HTML or PNG. It's nice to put it in book / blog post.

**Comment by Kungsgeten** [comment]
@namdnguyen @azzamsa I've started a new repository named [org-brain-export](https://github.com/Kungsgeten/org-brain-export). I think discussions focused on exporting could be moved there. A starting point could be: https://github.com/Kungsgeten/org-brain-export/issues/2

I'm closing this since I think export discussions could take place there.
