### ISSUE TITLE
Visualize (consistent portions of) the whole mind map

### ISSUE THREAD

**Issue by falematte** [Kungsgeten/org-brain#60]
I really would like to use org-brain as a mind-mapping tool for brainstorming (I believe this is crucial for all the people using the GTD system which are a consistent part of org-mode users) but the portion of the map which is currently visualized is too small (in my opinion) for this use... Is it possible to improve the visualization in order to be similar to other mind-mapping softwares like freemind...?

**Comment by Kungsgeten** [comment]
In theory that's absolutely possible. The problem (at least for me) would be to write the code which renders the entries and the connections. The current code for org-brain-visualize is kind of ugly, and visualizing a bigger portion would probably be even more complicated.

**Comment by falematte** [comment]
Just random brainstorming... What about emacs artist-mode functionalities for rendering the entries and the connections?

**Comment by Kungsgeten** [comment]
Not sure if `artist-mode` makes it easier to generate, but maybe? I think `artist-mode` is more for real time drawing by the user. `org-brain` is using the Emacs package `picture.el` right now to make rendering a bit easier.

I made a quick mockup of how a mind-map might look. Something like the following would probably be pretty easy to create. Notice though that it is a lot of unused space, and that it will start to look like a stair the more you "zoom out". My idea in this case would be that you can see parents, children, grand parents (and further up), grand children (and further down) and siblings, but it will probably be harder if you want to show the grand parents other children, or the grand childrens other parents.

```
PINNED: Pinned1  Pinned2
Friends: Friend1  Friend2  Friend3

Parent1
Parent2--Parent1-- Sibling 1
                   Sibling 2
                   Sibling 3
         Parent2-- Sibling 1
         Parent3
         Parent4-- Entry--Child1
                          Child2--Child1
                          |       Child2
                          |       Child3
                          Child3
                          Child4--Child1
                                  Child2
                                  Child3

```

**Comment by falematte** [comment]
This looks great! Any plan to implement it?

**Comment by Kungsgeten** [comment]
@falematte Yes I'll give it a shot. I haven't taken the time to do programming in my spare time the last few weeks, but hopefully I'll get inspired soon!

**Comment by Kungsgeten** [comment]
It is now possible to toggle to "mind map mode", by pressing `m`, while using `org-brain-visualize`. In this mode you can zoom out, in order to see more grandchildren and grandparents by pressing `-` and `z`. More info in the README.
