### ISSUE TITLE
Handling spaces in titles when adding nodes

### ISSUE THREAD

**Issue by rsuhada** [Kungsgeten/org-brain#63]
I'm really happy that org-brain can handle spaces in titles, but there is a small issue in commands like `org-brain-add-child` etc., where if I add a new child "Computer Games", then the tag "#+BRAIN_CHILDREN: Computer Games" (with space) is added. This means that two nodes are shown "Computer" and "Games" although only one file is created "Computer Games.org" (which is correct).

Manually changing  "#+BRAIN_CHILDREN: Computer Games" to  "#+BRAIN_CHILDREN: Computer%20 Games" fixes the display issue.

Could we have all `org-brain-add-*` commands automatically replace spaces in all nodes so that the tags are correct?

Thank you very much!

**Comment by Kungsgeten** [comment]
I wasn't aware that this bug existed, so thank you for reporting it! It should be fixed now :)

**Comment by rsuhada** [comment]
Thanks for the super fast response! Great, it works now!
