### ISSUE TITLE
Lock files show up in HELM of Brain Visualize

### ISSUE THREAD

**Issue by freddie-freeloader** [Kungsgeten/org-brain#66]
I am using org-brain through spacemacs, so I hope this is not spacemacs specific. :slightly_smiling_face: 

If I use `org-brain-visualize` while editing a file, that is part of the "org-brain", the HELM-dialog shows me also emacs lock file (e.g. `.#ideas`). Is there a way to prevent this? :smiley:

**Comment by Kungsgeten** [comment]
Hi! I've added a commit which should fix this (I hope). Please re-open this if it doesn't.

**Comment by freddie-freeloader** [comment]
Cool! This was super fast. :smiley:
