### ISSUE TITLE
Open current entry for editing -> empty 

### ISSUE THREAD

**Issue by bvhk** [Kungsgeten/org-brain#68]
Hi 

Thanks for sharing org-brain. It is a fantastic addition to org-mode that I use on almost daily basis. 
Installed the latest version from Melpa and started to work on a org-brain file with a couple of child entries. 
All org files are stored in ~/org/brain/
First time I created the org-brain file using the shortcut 'o' (org-brain-goto-current) opened the file in the split screen with the ID information. 
After closing emacs and trying it again it with org-brain-visualize and trying to edit an entry (with shortcut 'o') it opened an empty file in the split screen. 
When I open the created org files in emacs buffer first (so not using org-brain to select them) org-brain-goto-current does open the files with ID info. 
So there is a workaround by manually opening all org files in emacs, but I assume org-brain should be able to find and open the child files with IDs automatically.  

Using org-brain-update-id-locations resulted in "10 unique files scanned for IDs" but didn't solve the problem.

**Comment by Kungsgeten** [comment]
Good catch! A bit strange that I hadn't noticed this before. I've pushed a commit which should fix this.

**Comment by Kungsgeten** [comment]
I find it a bit strange that the fix works for me, but not for you. I tried with `emacs -Q` and it still worked.

**Comment by bvhk** [comment]
Removed the old version completely and installed the latest and now it works without a problem so it seems the issue was on my side, sorry for the confusion.
