### ISSUE TITLE
Customization - files extension and links

### ISSUE THREAD

**Issue by samspo** [Kungsgeten/org-brain#7]
Nice concept. Works well and interesting.

Would be interesting to allow customization of : 
- file extension (for instance, allow to use .txt files instead of .org files)
- links (for instance, be able to use wiki: instead of brain: )

**Comment by Kungsgeten** [comment]
Hi! Support for different file extensions is a good idea, I'll try to add that. Being able to customize the link type would lead to quite a bit of extra code, and could also lead to clashes with other packages (`org-wiki` uses the `wiki:` link type, for instance).

**Comment by samspo** [comment]
Thanks for the follow-up and the commit 640a66055c92d6509e0840e5228638c9ff138a6a
