### ISSUE TITLE
Hook on node creation

### ISSUE THREAD

**Issue by bdillahu** [Kungsgeten/org-brain#71]
(please forgive me, as I'm not a heavy elisp'er)

Looking at the code, it appears to me that when you are creating a new child/whatever node it is being written to the buffer directly without using any of the org-mode hooks/functionality.

I have an org-mode hook that writes a date property when I capture an item. I would love to somehow have this run when I create a new child or whatever.

i.e.:

  (add-hook 'org-capture-before-finalize-hook 'add-property-with-date-captured)

I'm not sure if there is already a way to do this that I'm not seeing, or maybe there would be a way for org-brain to create a node via org instead of manually?

Or something else :-)

**Comment by Kungsgeten** [comment]
It sounds like a good idea, I'll look into it. Happy holidays!

**Comment by Kungsgeten** [comment]
I've added `org-brain-new-entry-hook`. Please have a look and see if it works as you intend.

**Comment by bdillahu** [comment]
Well, it appears to be good, appreciate it!

In between times I made a change in my config that also seemed to work around things, so its a little tough for me to see if it's totally working for my use case (as the other config is covering for it, and I don't want to mess that up right now :-)).

Thanks for this, looks good!

Bruce

**Comment by bdillahu** [comment]
I know this is really late, but wanted to let you know I got to do some testing tonight (found another place I needed this function) and it worked like a champ. Thanks!
