### ISSUE TITLE
Refile to brain

### ISSUE THREAD

**Issue by Zetagon** [Kungsgeten/org-brain#74]
I must first say that I think org-brain is potentially just what I need. I have a little bash script that captures the text I highlight to a file called capture.org . My plan was then to refile the captured stuff  into org-brain but it isn't obvious how it should be done. I found somewhere that it could be done with some elisp but that it would be slow. My question is: is there a way to refile headlines into org-brain using the org-brain interface?

**Comment by Kungsgeten** [comment]
There's no built-in way to do this, so you'd have to do some hacking. It sounds useful though, so I'll look into it. Happy holidays!

**Comment by Zetagon** [comment]
Merry Christmas! Time to do some hacking then!

**Comment by Kungsgeten** [comment]
I've now added the command `org-brain-refile`, which hopefully should cover your needs! If you need other functionality you could look at that function for inspiration :)
