### ISSUE TITLE
Symbol's function definition is void.

### ISSUE THREAD

**Issue by BEpresent** [Kungsgeten/org-brain#76]
First of all, I really like the concept of org-brain very much, it is a great idea and I hope it will continue to evolve.

I have installed org-mode in spacemacs, however org-brain-visualize does not seem to work,

`Symbol's function definition is void: aa2u
`

Creating a link seems to work at first, however, after a restart the link does not anymore, and it wants to create a new heading:

`No match - create this as a new heading?`

From your readme, the following is also not accepted in .spacemacs (emacs complains). It only works by inserting these lines into the brackets of  (defun org-brain/init-org-brain () )

```
(use-package org-brain :ensure t
  :init
  (setq org-brain-path "directory/path/where-i-want-org-brain")
  ;; For Evil users
  (eval-after-load 'evil
    (evil-set-initial-state 'org-brain-visualize-mode 'emacs))
  :config
  (setq org-id-track-globally t)
  (setq org-id-locations-file "~/.emacs.d/.org-id-locations")
  (push '("b" "Brain" plain (function org-brain-goto-end)
          "* %i%?" :empty-lines 1)
        org-capture-templates)
  (setq org-brain-visualize-default-choices 'all)
  (setq org-brain-title-max-length 12))
```

May be, it was not installed correctly? ( `dotspacemacs-additional-packages` in .spacemacs)

**Comment by Kungsgeten** [comment]
I haven't used spacemacs, so I'm sorry to say I have no idea what kind of special things it uses during the setup. It seems that you're using the function `aa2u`, which is defined in the package `ascii-art-to-unicode`, maybe you've read about it in the README of `org-brain`? Anyway it seems like you haven't installed that package.

**Comment by BEpresent** [comment]
You are exactly right, installed aa2u and it worked, thanks! (still new to emacs/spacemacs).

The problem with the links remains, 
e.g. if a testlink.org exists and org-brain creates a link [[brain:testlink]testlink]], it works at first, but stops  working after restarting. It then asks No match - create this as a new heading?

If this is answered with yes, it creates an org-mode heading * brain:testlink, which does not contain any links.

**Comment by BEpresent** [comment]
The solution was to update the id-locations, now it seems to work (did that before, not sure why it worked this time. Thanks!

**Comment by Kungsgeten** [comment]
Yes, that's a common solution in org-brain when things are acting strange :) Glad that it worked out!
