### ISSUE TITLE
Child/parent completion

### ISSUE THREAD

**Issue by bdillahu** [Kungsgeten/org-brain#79]
It seems I can only get Friends to do auto-complete... nothing is ever allowed for Children/parents.

Am I doing something wrong, or does that not work?

Thanks!

**Comment by Kungsgeten** [comment]
Hmm, that's very strange. What package are you using for completion (if any)? How are you trying to add the parents/children (what commands are you using, and where)?

**Comment by bdillahu** [comment]
Well, I'm sorry, but I'm reasonably new to emacs (after years on the VIM dark side) and I'm not sure I know what is doing the completion... I have some completion stuff (ido) for files paths, etc., but it doesn't act like it's in use for org-brain. 

If there is some magic command to find that, let me know and I'll check.

As for recreating, say I have a node/item selected and in view, hit "p" or "h/*" and it prompts at the bottom and I can't seem to complete (or find) anything. If I do a "friend" then I can type in "House::" (the top level of the file) and complete all the items reasonably well.

**Comment by Kungsgeten** [comment]
No need to be sorry, welcome to the Emacs world :) The `h` / `*` command doesn't have completion, since it always adds a new (local) child entry. If you'd like to add an existing entry as a child (or create a new non-local entry as a child) you should use the `c` command. It should be possible to get completion using the `p` command though...

**Comment by bdillahu** [comment]
OK, so use "c" instead of h/* - got it...

As for parents... well, not sure what happened, but it seems to be working now, so either operator error (probably), or something was temporarily hosed and a restart fixed it. 

I would just close this and thanks for the info!

Bruce

**Comment by Kungsgeten** [comment]
Yes, `c` is for external children (usually files or headlines in another tree), while `h` is for adding a subheading to the entry; a local child. Glad I could help!
