### ISSUE TITLE
Edit visualize buffer ala wdired

### ISSUE THREAD

**Issue by ryjm** [Kungsgeten/org-brain#82]
When you invoke `wdired` in a dired buffer, you can edit the displayed filenames directly in the buffer, and they will be renamed upon saving. Would be cool if org-brain could do the same.

**Comment by Kungsgeten** [comment]
It is a cool idea. It is somewhat similar to #81 I guess, but would happen inside the buffer?

**Comment by Kungsgeten** [comment]
Even though its not quite what this feature request asks for, I think a recent commit provides about the same functionality (but a lot simpler, which means less code). You could now turn on `org-brain-visualize-follow` by pressing `V` when visualizing. Visualized entries are then automatically opened in another window, and you could simply switch to them and edit.
