### ISSUE TITLE
Feature: represent the map using symbolic links

### ISSUE THREAD

**Issue by baygeldin** [Kungsgeten/org-brain#88]
Hi! First of all, thank you for such an amazing package. I really appreciate the idea behind it in that it's future proof: plain text files, no database, it's easy to both integrate and remove the package from one's note taking workflow.

Concept maps are a great compromise between hierarchy and tags: they are more flexible than hierarchical structures and less verbose than tags (which are also hard to maintain). However, current filesystems are hierarchical by nature and any attempts to fit complex data to it fall apart inevitably. This is especially true for note taking (e.g. "should I put Cryptocurrencies to Finances folder or to Software Engineering one?"). I believe that this problem is solvable with your package. How hard would it be to generate folder structure based on `org-brain` concept map and put notes' symlinks to it? Imagine I have a flat folder with a bunch of interlinked notes. We can create a topmost folder for a given parent node, create a symlink to the node's file inside it (e.g. `index.org`), put all child nodes in there as well (or create a similar subfolder in case the child has its own childs). Jump thoughts can be put into a separate directory near child files and folders. This way it would be easy to explore the notes database using any file manager of choice and perform bulk changes on the files (or just copy them with `cp -Lr`).

This is just an idea, nothing that I consider "must have". The only thing I'm missing now is some kind of review process for my notes, but I guess it's out of scope of the project.

**Comment by Kungsgeten** [comment]
I think it would be doable, if you know what you want :) The problem is the concepts of folders and files in a file system; because in `org-brain` there are no folders! There's just entries which are linked to another in different ways, and the entries may contain text. It could be possible to represent this in a file system where every entry is a folder, and the folder can contain symbolic links to other folders (children), and perhaps a text file holding the entry's content.

**Comment by baygeldin** [comment]
That's what I was thinking of. I really like the idea of showing only parts of map in the visualization, but sometimes it's desirable to explore the whole map and I thought that such file structure based on symlinks would be quite handy in this case. Anyway, seems like recent commits have already added the functionality for visualizing the whole map, so I should check it out! Thank you. I'll close this for now (at least until I find some other useful use cases).
