### ISSUE TITLE
About readme

### ISSUE THREAD

**Issue by VonFry** [Kungsgeten/org-brain#89]
In readme,
```
  (eval-after-load 'evil
    (evil-set-initial-state 'org-brain-visualize-mode 'emacs))
```

But `eval-after-load` is a function, its second argument will be run when we called.

Use `with-eval-after-load` to instead which is a macro or change the second args into string, symbol or lambda expression.

At least, on my mac is it.

**Comment by Kungsgeten** [comment]
Thanks! I've changed it to `with-eval-after-load`.
