### ISSUE TITLE
Handle multi-part extensions such as .org.gpg

### ISSUE THREAD

**Issue by AndyBold** [Kungsgeten/org-brain#9]
I've been trying to figure this out, but my lisp-fu is weak.

I use `org-crypt` to encrypt my org files with GPG. This results in a file extension of .org.gpg.

I have `org-brain-files-extension` set to "org.gpg".

If I create a new file via `org-brain-open` then emacs does the right thing when I save the new file, and encrypts it. E.g., if I create a new brain file called 'index' then it is saved as 'index.org.gpg', and encrypted.

org-brain uses `file-name-sans-extension` in `org-brain-parth-entry-name` to remove filename extensions when listing them for `org-brain-open` (and other places), but that function only removes the ".gpg" part of the path. 

So when I use `org-brain-open` after creating and saving some files, the file list looks like:

index.org
somethingelse.org

And so on. If I try to open one of those files than a filename of, for example, "index.org.org.gpg" is assigned to a new, empty, buffer.

**Comment by Kungsgeten** [comment]
Thanks for reporting this, I hadn't considered multi-part extensions. I've changed `org-brain-path-entry-name`, so hopefully it'll work now. Please try it out!

**Comment by AndyBold** [comment]
I just tested and it looks like that is working perfectly.

Thank you for the rapid response!
