### ISSUE TITLE
Entry fontification?

### ISSUE THREAD

**Issue by dieggsy** [Kungsgeten/org-brain#90]
I really like the idea of org-brain, but I find entries harder to parse than the original org-mode. It'd be nice if things like emphasis markers, links, source blocks, drawers, etc. were fontified as they are in org-mode.

**Comment by Kungsgeten** [comment]
I agree! I've thought of it myself before and I'll try to make the entries use org-mode's fontification. Thanks for reminding me!

**Comment by Kungsgeten** [comment]
Should be fixed now :)
