### ISSUE TITLE
Top level headline?

### ISSUE THREAD

**Issue by tunesmith** [Kungsgeten/org-brain#91]
Would it be possible to have a file's top level still be treated as a headline?

For instance, it is nice to be able to split the brain apart by file, but to still have each entry be a "headline" so that it can be made a TODO, or so a tag can be applied to it, etc. (I started with a test brain and started splitting it apart into new files every couple of levels because it felt cleaner and more organized, and then I realized I couldn't tag half of my entries.)

Could this perhaps be accomplished by just making the top part of the file an actual first-level headline, rather than a "title" that isn't a headline?

**Comment by Kungsgeten** [comment]
A solution for this (kind of) might be to have an option to not treat files as entries. Then if you add a new file entry, it would just create the file and a top level heading. It seems useful, so I'll see what I can do :)

**Comment by Kungsgeten** [comment]
You can now set `org-brain-include-file-entries` to `nil`, which (sort of) will give the behavior you describe.
