### ISSUE TITLE
Set tags on files

### ISSUE THREAD

**Issue by drym3r** [Kungsgeten/org-brain#93]
If you're try to tag a file and not a headline, it says "org-brain-set-tags: Can only set tags on headline entries". But since it's possible to tag files with `#+tags: emacs`, it would be nice to have it.

PD: Thanks for your work, I'm just beginning to use org-brain and I already love it!

**Comment by Kungsgeten** [comment]
[From what I understand](https://orgmode.org/manual/Setting-tags.html) `#+tags: emacs` doesn't tag the file with `emacs`, it insteads sets `emacs` as (one of) the default tag(s) when using tag completion in that `org-mode` file. [Another keyword](https://orgmode.org/manual/Tag-inheritance.html) is `#+FILETAGS:` which makes all the headings in the file inherit the provided tags.

What is your use case for wanting to give tags to files?

**Comment by drym3r** [comment]
You're right, I mistyped the name. I was thiking about Filetags.

**Comment by Kungsgeten** [comment]
It is now possible to use `org-brain-set-tags` also on both file- and headline entries :) For file entries, it will use `#+FILETAGS`.

**Comment by drym3r** [comment]
Cool! Thank you very much.
