### ISSUE TITLE
Slow performance of org-brain-visualize

### ISSUE THREAD

**Issue by rsuhada** [Kungsgeten/org-brain#94]
I'm slowly porting my Brain to org-brain. I only have 400 entries, but `org-brain-visualize` takes approx. 4s to visualize. Is this usual or do I have some issue on my side?

I've checked an older thread (https://github.com/Kungsgeten/org-brain/issues/16), the conclusion was that it should be ~1s (not sure about num. of children).

Setting `org-brain-visualize-default-choices` to `root` helps a lot, but I do want/need to search all my notes, so this is not really an option.

Thank you!

**Comment by Kungsgeten** [comment]
I'm not sure how much it helps, but you can try setting `org-brain-file-entries-use-title` to `nil` and see if that helps. For me `org-brain-visualize` is slow the first time I run it in an Emacs session, but faster the next times.

**Comment by rsuhada** [comment]
Thanks - it did help (quite a lot!). Much faster startup now!

**Comment by Kungsgeten** [comment]
Nice to hear! I've also optimized the code a bit, when fetching headline entries, so if you haven't updated recently that might help.
