### ISSUE TITLE
Documentation Request: Better Explanation of "Org-Brain Headline File"

### ISSUE THREAD

**Issue by naclander** [Kungsgeten/org-brain#96]
I've been reading up on this emacs package and it looks really interesting. When playing around with it, I keep seeing refrences to "Headline Files", but couldn't find any documentation in the README describing what they are, or in the [latest video](https://www.youtube.com/watch?v=3EGOwfWok5s) posted about org brain.

On a related note, the reason I was interested on Org-Brain headline files is because apparently those are the files with an org-brain ID. I the quick org-brain I created for test purposes did not have *any* files in it which had an org-brain id in their metadata.

Thanks for the cool looking package, I'm hoping I can start using it on a more daily basis once I work out some of the kinks.

**Comment by Kungsgeten** [comment]
_Headline files_ aren't a concept, but _headline entries_ are. In `org-brain` there are two types of entries: all org-files inside the `org-brain-path` are considered as entries; and all headlines with an ID inside these files are also considered as entries (these are the _headline entries_). I should probably describe this in some concise way in the README.

In order to create a headline entry, from `org-mode`, you simply create a new headline and use `M-x org-id-get-create` to give it an ID.

**Comment by Kungsgeten** [comment]
If I were to design org-brain from scratch, I would probably the file entry concept, and only support headline entries. From the beginning there were only file entries. There's actually a feature request #91 with an idea to turn the file entries off.

**Comment by Kungsgeten** [comment]
I've now updated the README with some info on headline vs file entries.

**Comment by naclander** [comment]
Ok, I've had a chance to play around with org-brain more ( which again, I think is a great emacs package ) and I think I understand the concept of org-brain headline entries. 

I found out children can be created either as new files, or as entries of a file ( for example, using the `filename::entry-name` name when creating a child entry ). The way I was creating children was without headlines, so naturally none of the files had any IDs, which caused some confusion. 

I'm not really sure why you decided to implement org-brain this way. I understand that having these two "types of children" in org-brain could be useful, but it ended up being really confusing. 

Part of the problem definitely stemmed from not having all the information available in the readme, although I understand org-brain is at this point a fairly large program with many users potentially choosing to use it in different ways. So capturing all of that in documentation is no small task.

I think though that that's exactly the reason to remove file entries ( or headline entries, I don't really care ). As long as the interface to the user is a little clearer, especially when just starting to learn org-brain, I think any design decision should be good. I'll make sure to keep an eye out  on #91 . Thanks again for the work on org-brain.
