### ISSUE TITLE
org-brain-visualize does not work

### ISSUE THREAD

**Issue by mikmakmuk** [Kungsgeten/org-brain#97]
I'm running org-brain-20180409.442 on emacs 25.3.1.
When calling `org-brain-visualize` and try to open an entry, I get the following trace:
`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match(":" nil 0)
  split-string(nil ":" t)
  org-brain-text("work")
  org-brain--vis-text("work")
  org-brain-visualize("work")
  funcall-interactively(org-brain-visualize "work")
  call-interactively(org-brain-visualize nil nil)
  command-execute(org-brain-visualize)`

`org-brain-visualize-random` works fine.

Not sure how I can debug this further (I'm new to emacs and Lisp).

**Comment by Kungsgeten** [comment]
It was due to a bug introduced in the latest commit, I've fixed it now. I should really start writing unit tests... Thanks for notifying me about this!

**Comment by mikmakmuk** [comment]
Jup, works again. Thanks for the quick fix!
